use super::SignatureHit;
use crate::analysis::OffsetMap;
use std::collections::BTreeMap;

/// Map a DLL filename to the namespace stem we expose it under.
///
/// `client.dll` -> `client`         (cs2::offsets style)
/// `client.dll` -> `client_dll`     (cs2_dumper style, matches a2x)
fn ns_short(module: &str) -> String {
    module.trim_end_matches(".dll").replace('.', "_")
}

fn ns_a2x(module: &str) -> String {
    module.trim_end_matches(".dll").replace('.', "_") + "_dll"
}

/// Sanitise a signature `name` field into a valid C++/Rust identifier.
/// Some entries in the database carry C++-style scoping like
/// `Engine::PVSManager_ptr` — that token can't appear inside a
/// `namespace { ... }` body without a syntax error, so flatten it.
fn sanitise_ident(name: &str) -> String {
    name.replace("::", "_")
        .replace(|c: char| !(c.is_ascii_alphanumeric() || c == '_'), "_")
}

/// Generate `sdk/offsets.hpp`.
///
/// The file holds two side-by-side namespace trees so any consumer
/// can pick the convention they already use:
///
/// * `cs2::offsets::<module>`        — every RIPREL signature hit
///   (`GameRules_ptr`, `LocalPlayerController_ptr`, …) keyed by the
///   exact name from `signatures::database`. This is the dumper's
///   own preferred layout.
/// * `cs2_dumper::offsets::<module>_dll` — drop-in compatible with
///   `a2x/cs2-dumper`'s `offsets.hpp`. Sourced from the live
///   pattern-scan analysis pass (`analysis::offsets`) so it carries
///   the canonical `dwLocalPlayerPawn`, `dwViewAngles`, `dwEntityList`,
///   `dwGameEntitySystem_highestEntityIndex`, `dwGlobalVars`, …
///   names every public CS2 cheat already uses.
pub fn render_offsets_hpp(hits: &[SignatureHit], analysis: &OffsetMap) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cs2-sdk - https://cs2-sdk.com\n");
    s.push_str("// Resolved global addresses from the signature + offset passes.\n");
    s.push_str("//\n");
    s.push_str("// Two namespace trees are emitted:\n");
    s.push_str("//   cs2::offsets::<module>          — signature-resolved interface/global pointers\n");
    s.push_str("//   cs2_dumper::offsets::<module>_dll — a2x/cs2-dumper drop-in (dwXxx names)\n");
    s.push_str("#pragma once\n\n");
    s.push_str("#include <cstddef>\n");
    s.push_str("#include <cstdint>\n\n");

    // -----------------------------------------------------------------
    // Block A: cs2::offsets::<module>  (signatures pass)
    // -----------------------------------------------------------------
    let mut by_module: BTreeMap<&str, Vec<&SignatureHit>> = BTreeMap::new();
    for h in hits.iter().filter(|h| h.found && h.resolve == "riprel") {
        by_module.entry(h.module.as_str()).or_default().push(h);
    }

    s.push_str("namespace cs2::offsets {\n");
    for (module, items) in &by_module {
        s.push_str(&format!("    // Module: {}\n", module));
        s.push_str(&format!("    namespace {} {{\n", ns_short(module)));

        // Deduplicate sanitised names so two entries that collapse to
        // the same identifier (e.g. `Foo::Bar` and `Foo_Bar`) don't
        // cause a redefinition error.
        let mut seen: BTreeMap<String, u32> = BTreeMap::new();
        for h in items {
            if let Some(rva) = h.rva {
                let mut ident = sanitise_ident(&h.name);
                let count = seen.entry(ident.clone()).or_insert(0);
                if *count > 0 {
                    ident = format!("{}_{}", ident, *count);
                }
                *count += 1;
                s.push_str(&format!(
                    "        constexpr uintptr_t {} = 0x{:X};\n",
                    ident, rva
                ));
            }
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n\n");

    // -----------------------------------------------------------------
    // Block B: cs2_dumper::offsets::<module>_dll  (a2x layout)
    // -----------------------------------------------------------------
    s.push_str("// a2x/cs2-dumper drop-in layout — every public CS2 cheat\n");
    s.push_str("// already includes a header structured exactly like this,\n");
    s.push_str("// so this block lets that code consume our output unchanged:\n");
    s.push_str("//   using namespace cs2_dumper::offsets::client_dll;\n");
    s.push_str("namespace cs2_dumper {\n");
    s.push_str("    namespace offsets {\n");
    for (module, entries) in analysis {
        s.push_str(&format!("        // Module: {}\n", module));
        s.push_str(&format!("        namespace {} {{\n", ns_a2x(module)));
        for (name, rva) in entries {
            s.push_str(&format!(
                "            constexpr std::ptrdiff_t {} = 0x{:X};\n",
                name, rva
            ));
        }
        s.push_str("        }\n");
    }
    s.push_str("    }\n");
    s.push_str("}\n");

    s
}

/// `sdk/offsets.json` — machine-readable mirror of the a2x block.
pub fn render_offsets_json(analysis: &OffsetMap) -> String {
    // Convert RVAs to hex strings so the JSON matches a2x's emitter byte for byte.
    let mut root: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    for (module, entries) in analysis {
        let mut inner = BTreeMap::new();
        for (name, rva) in entries {
            inner.insert(name.clone(), format!("0x{:X}", rva));
        }
        root.insert(module.clone(), inner);
    }
    serde_json::to_string_pretty(&root).unwrap_or_default()
}

/// `sdk/offsets.rs` — Rust mirror of the a2x block.
pub fn render_offsets_rs(analysis: &OffsetMap) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cs2-sdk - https://cs2-sdk.com\n");
    s.push_str("#![allow(non_upper_case_globals, unused)]\n\n");
    s.push_str("pub mod cs2_dumper {\n");
    s.push_str("    pub mod offsets {\n");
    for (module, entries) in analysis {
        s.push_str(&format!("        // Module: {}\n", module));
        s.push_str(&format!("        pub mod {} {{\n", ns_a2x(module)));
        for (name, rva) in entries {
            s.push_str(&format!("            pub const {}: usize = 0x{:X};\n", name, rva));
        }
        s.push_str("        }\n");
    }
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}
