// Auto-generated by cs2-universal-dumper. Do not edit.
//
// Single-file Rust amalgamation. Drop the session's `sdk/` and
// `signatures/` directories side-by-side and add `mod cs2sdk;`
// pointing at this file.

#![allow(non_upper_case_globals, non_snake_case, dead_code)]

pub const CS2_BUILD: u32 = 14160;

#[path = "../signatures/signatures.rs"] pub mod signatures;
