// Auto-generated by cs2-universal-dumper. Do not edit.
// Each constant is an IDA-style byte pattern; scan it at
// runtime with your favourite pattern scanner.
#![allow(non_upper_case_globals, non_snake_case, dead_code)]

pub mod animationsystem {
    pub const Animation__ShouldUpdateSequences: &str = "48 89 5C 24 08 48 89 74 24 18 57 48 83 EC 20 49";
    pub const AnimationSystemUtils_ptr: &str = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 83 EC 28 48 8B CA 48 8D 15";
}

pub mod client {
    pub const AddNametagEntity: &str = "40 55 53 56 48 8D AC 24 B0 FC FF FF 48 81 EC 50";
    pub const AddStattrakEntity: &str = "48 8B C4 48 89 58 08 48 89 70 10 57 48 83 EC 50 33 F6 8B FA";
    pub const AnimGraphRebuild: &str = "40 55 56 48 83 EC 28 4C 89 74 24 58 48 8B F1 80";
    pub const ApplyEconCustomization: &str = "48 89 5C 24 08 57 48 83 EC 20 8B FA 48 8B D9 E8 ? ? ? ? 48 8B CB E8 ? ? ? ? 48 85 C0 74";
    pub const AutowallInit: &str = "40 53 48 83 EC 20 48 8B D9 48 81 C1 D8 0D 00 00";
    pub const AutowallTraceData: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 50 48 8B 09 49";
    pub const AutowallTracePos: &str = "40 55 56 41 54 41 55 41 57 48 8B EC 48 83 EC 60";
    pub const BulkRegenIterator: &str = "57 48 83 EC 40 0F B6 F9 E8 ? ? ? ? 48 85 C0";
    pub const CAM_ThinkReturn: &str = "BA 04 00 00 00 FF 15 E6 A1 5E 01 84 C0 0F 84 C2";
    pub const CAttributeStringFill: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 20 33 F6 0F 57 C0 0F";
    pub const CAttributeStringInit: &str = "48 8B C2 48 83 C8 02 45 84 C0 48 0F 44 C2 48 89 41 08 48 8D 05 1F B4 3A";
    pub const CBaseEntity_ChangeModel: &str = "40 53 48 83 EC 20 48 8B D9 4C 8B C2 48 8B 0D ED";
    pub const CBaseEntity_TakeDamageOld: &str = "40 55 53 56 57 41 54 48 8D 6C 24 E0 48 81 EC 20";
    pub const CBaseModelEntity_SetBodygroup: &str = "85 D2 0F 88 ? ? ? ? 55 53 56 41 56 48 8B EC";
    pub const CBodyComponent: &str = "48 83 EC 38 48 8B 05 ? ? ? ? 48 85 C0 0F 85 ? ? ? ? 48 89 5C 24 40 B9 50 00 00 00 48 89 6C 24 48 4C 89 64 24 30 4C 89 74 24 28 4C 89 7C";
    pub const CBodyComponentSkeletonInstance: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 8B 0D 36 15";
    pub const CBufferStringInit: &str = "48 89 5C 24 10 57 48 83 EC 30 8B 41 04 48 8D 79";
    pub const CCSGOInput__CreateMove: &str = "48 8B C4 4C 89 40 18 48 89 48 08 55 53 41 54 41";
    pub const CCSGameRules: &str = "4C 8D 05 ? ? ? ? 48 8D 15 ? ? ? ? 48 8D 0D 6B B2 21";
    pub const CCSGameRulesProxy: &str = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 5B E5 0F";
    pub const CCSInventoryManager__EquipItemInLoadout: &str = "48 89 5C 24 08 48 89 6C 24 18 48 89 74 24 20 89 54 24 10 57 41 54 41 55 41 56 41 57 48 83 EC 70";
    pub const CCSPlayerController: &str = "40 55 41 56 41 57 48 8B EC 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 1E 03 00";
    pub const CCSPlayerController: &str = "40 55 41 56 41 57 48 8B EC 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 1E 03 00";
    pub const CCSPlayerController_ActionTrackingServices: &str = "40 55 41 56 41 57 48 8B EC 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 1E 03 00";
    pub const CCSPlayerController_DamageServices: &str = "40 55 41 56 41 57 48 8B EC 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 1E 03 00";
    pub const CCSPlayerController_InGameMoneyServices: &str = "40 55 41 56 41 57 48 8B EC 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 1E 03 00";
    pub const CCSPlayerController_InventoryServices: &str = "40 55 41 56 41 57 48 8B EC 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 1E 03 00";
    pub const CCSPlayerInventory__GetItemInLoadout: &str = "40 55 48 83 EC 30 49 63 E8 ? ? ? ? 87 94 01";
    pub const CCSPlayerPawn: &str = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 1B 6C C3";
    pub const CCSPlayer_BulletServices: &str = "40 53 48 83 EC 50 8B 15 ? ? ? ? 48 8B D9 65 48 8B 04 25 58 00 00 00 B9 98 00 00 00 48 8B 04 D0 8B 04 01 39 05 DE 98";
    pub const CCSPlayer_BulletServices: &str = "40 53 48 83 EC 50 8B 15 ? ? ? ? 48 8B D9 65 48 8B 04 25 58 00 00 00 B9 98 00 00 00 48 8B 04 D0 8B 04 01 39 05 DE 98";
    pub const CCSPlayer_CameraServices: &str = "48 89 5C 24 08 57 48 83 EC 30 E8 ? ? ? ? 8B 15 CB 48 D3";
    pub const CCSPlayer_HostageServices: &str = "40 53 48 83 EC 50 8B 15 ? ? ? ? 48 8B D9 65 48 8B 04 25 58 00 00 00 B9 98 00 00 00 48 8B 04 D0 8B 04 01 39 05 DE 98";
    pub const CCSPlayer_ItemServices: &str = "40 53 48 83 EC 50 8B 15 ? ? ? ? 48 8B D9 65 48 8B 04 25 58 00 00 00 B9 98 00 00 00 48 8B 04 D0 8B 04 01 39 05 AE 0D";
    pub const CCSPlayer_MovementServices: &str = "48 83 EC 28 8B 0D ? ? ? ? 65 48 8B 04 25 58 00 00 00 BA 98 00 00 00 48 8B 04 C8 8B 04 02 39 05 63 44 AC 01 0F 8F 36";
    pub const CCSPlayer_MovementServices: &str = "48 83 EC 28 8B 0D ? ? ? ? 65 48 8B 04 25 58 00 00 00 BA 98 00 00 00 48 8B 04 C8 8B 04 02 39 05 63 44 AC 01 0F 8F 36";
    pub const CCSPlayer_MovementServices_CheckJumpButton: &str = "4C 89 44 24 18 55 56 41 56 48 8D AC 24 70 EC FF";
    pub const CCSPlayer_PingServices: &str = "48 89 5C 24 18 55 48 8B EC 48 83 EC 60 8B 15 AD";
    pub const CCSPlayer_RunCommand_Context: &str = "48 8B C4 48 81 EC C8 00 00 00 48 89 58 10 48 89";
    pub const CCSPlayer_UseServices: &str = "48 89 5C 24 08 57 48 83 EC 30 E8 ? ? ? ? 8B 15 AB 23 CC";
    pub const CCSPlayer_WaterServices: &str = "48 83 EC 28 8B 0D ? ? ? ? 65 48 8B 04 25 58 00 00 00 BA 98 00 00 00 48 8B 04 C8 8B 04 02 39 05 5B D4 A8 01 0F 8F 43";
    pub const CCSPlayer_WeaponServices: &str = "48 83 EC 28 8B 0D ? ? ? ? 65 48 8B 04 25 58 00 00 00 BA 98 00 00 00 48 8B 04 C8 8B 04 02 39 05 53 E6 A8 01 0F 8F C4";
    pub const CCSPlayer_WeaponServices: &str = "48 83 EC 28 8B 0D ? ? ? ? 65 48 8B 04 25 58 00 00 00 BA 98 00 00 00 48 8B 04 C8 8B 04 02 39 05 53 E6 A8 01 0F 8F C4";
    pub const CCSWeaponBase: &str = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 8B 86 06";
    pub const CCSWeaponBaseGun: &str = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 EB 85 06";
    pub const CCSWeaponBaseVData: &str = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 8B 81 88";
    pub const CCollisionProperty: &str = "48 83 EC 58 83 F9 01 0F 85 ? ? ? ? 48 89 5C 24 60 48 8D 05 47 1C 81";
    pub const CCompositeMaterialManager_AddPanoramaPanelRenderRequest_Caller: &str = "41 2B C4 41 89 07 48 85 F6 74 7E 49 8B 5F 08 49";
    pub const CDecoyProjectile: &str = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 7B 98 09";
    pub const CEconItemSchema__GetAttributeDefinitionByName: &str = "48 89 5C 24 10 48 89 6C 24 18 57 41 56 41 57 48 83 EC 60 48";
    pub const CEconItemView__GetCustomPaintKitIndex: &str = "48 89 5C 24 08 57 48 83 EC 40 8B 15 ? ? ? ? 48 8B F9 65 48 8B 04 25 58 00 00 00 B9 98 00 00 00 48 8B 04 D0 8B 04 01 39 05 22 1B 31 01 0F 8F";
    pub const CFlashbangProjectile: &str = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 6B 76 80";
    pub const CFogController: &str = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 8B 8A 56";
    pub const CGameEntitySystem__OnAddEntity: &str = "48 89 74 24 10 57 48 83 EC 20 41 B9 FF 7F 00 00 41 8B C0 41 23 C1 48 8B F2 41 83 F8 FF 48 8B F9 44 0F 45 C8 41 81 F9 00 40 00 00 73 0D FF 81 90";
    pub const CGameEntitySystem__OnRemoveEntity: &str = "48 89 74 24 10 57 48 83 EC 20 41 B9 FF 7F 00 00 41 8B C0 41 23 C1 48 8B F2 41 83 F8 FF 48 8B F9 44 0F 45 C8 41 81 F9 00 40 00 00 73 08 FF 89 90";
    pub const CGameSceneNode: &str = "41 56 48 83 EC 30 4C 8B F2 85 C9 74 25 83 F9 06 74 09 33 C0 48 83 C4 30 41 5E C3 48 8B 02 49 8B CE 48 8D 54 24 58 FF 10 48 8B 00 48 83 C4 30 41";
    pub const CGameSceneNode_BuildBoneMergeWork: &str = "40 55 56 57 41 54 41 55 41 56 41 57 48 83 EC 50 48 8D 6C 24 50 80 A1 06";
    pub const CGameSceneNode_PerformBatchedInvalidatePhysicsRecursive: &str = "40 57 48 81 EC 90 00 00 00 84 C9 74 4D BF 01 00";
    pub const CGameSceneNode_StartHierarchicalAttachment: &str = "48 89 5C 24 10 48 89 6C 24 18 48 89 74 24 20 57 41 54 41 55 41 56 41 57 48 83 EC 30 48 8B F9 8B";
    pub const CGameTrace_TraceShape_Client: &str = "48 89 5C 24 20 48 89 4C 24 08 55 57 41 54 41 55";
    pub const CGlowProperty: &str = "48 83 EC 58 83 F9 01 0F 85 ? ? ? ? 48 8D 05 ? ? ? ? C7 44 24 30 00 00 00 80 89 4C 24 28 4C 8D 05 ? ? ? ? 48 89 44 24 48 48 8D 4C 24";
    pub const CGlowProperty_OnGlowTypeChanged: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8B 05 32 F8";
    pub const CHEGrenadeProjectile: &str = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 CB 75 80";
    pub const CInputPtrGlobal: &str = "4C 8B 05 ? ? ? ? 41 8B 80 50 0B 00 00 85 C0";
    pub const CMolotovProjectile: &str = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 9B 96 09";
    pub const CPaintKitDefinitions_FindOrCreateByName: &str = "48 89 5C 24 08 48 89 6C 24 18 56 57 41 56 48 81 EC 50 01 00";
    pub const CPaintKitDefinitions_LoadDefaultKit: &str = "48 89 6C 24 20 56 57 41 54 41 55 41 57 48 81 EC";
    pub const CPostProcessingVolume: &str = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 FB 3C 54";
    pub const CS2ItemEditor_BuildTemplateMaterialFromFile: &str = "48 89 54 24 10 55 53 41 55 41 57 48 8D AC 24 18";
    pub const CSBaseGunFireData_fn: &str = "48 8B C4 55 53 56 57 41 54 41 55 41 56 41 57 48 8D 68 A8 48";
    pub const CSGOInput_CreateMove: &str = "48 8B C4 4C 89 40 18 48 89 48 08 55 53 41 54 41";
    pub const CSGOInput_ptr: &str = "48 8B 0D ? ? ? ? 4C 8B C6 8B 10 E8";
    pub const CSGOInput_resolved: &str = "48 8B 0D ? ? ? ? 8B 10 E8 ? ? ? ? 45 32 FF";
    pub const CSkeletonInstance: &str = "40 57 48 83 EC 20 48 8B FA 85 C9 74 23 83 F9 06 74 08 33 C0 48 83 C4 20 5F C3 48 8B 02 48 8B CF 48 8D 54 24 48 FF 10 48 8B 00 48 83 C4 20 5F C3";
    pub const CSkeletonInstance__SetMeshGroupMask: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8D 99 50 01";
    pub const CSkeletonInstance_GetTransformsForHitboxList: &str = "48 89 5C 24 18 55 56 57 41 55 41 57 48 81 EC A0";
    pub const CSkeletonInstance_OnBodyGroupChoiceChanged: &str = "48 89 5C 24 08 57 48 83 EC 20 49 63 D8 49 8B F9";
    pub const CSkeletonInstance_OnSkeletonModelChanged: &str = "49 8B 00 48 89 81 B8 00 00 00 C6 81 B0 00 00 00";
    pub const CSkeletonInstance_PostDataUpdate: &str = "48 8B C4 4C 89 40 18 89 50 10 55 57 48 8D A8 68";
    pub const CSkeletonInstance_SetMaterialGroup: &str = "3B 91 C4 03 00 00 74 24 89 91 C4 03 00 00 48 8B";
    pub const CSkeletonInstance_SetMeshGroupMask: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 49 8B 00 49 8B";
    pub const CSmokeGrenadeProjectile: &str = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 FB 95 09";
    pub const CSource2Client_Shutdown: &str = "48 89 5C 24 08 55 56 57 41 54 41 55 41 56 41 57 48 81 EC 40";
    pub const CTonemapController2: &str = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 CB FD 58";
    pub const CUtlVector_CompositeMaterialInput_AddToTail: &str = "41 B9 88 02 00 00 8B 57 14 81 E2 FF FF FF 3F 8D 71 01 44 8B";
    pub const C_AttributeContainer: &str = "41 56 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 C7 02";
    pub const C_BaseEntity: &str = "48 89 5C 24 10 48 89 74 24 18 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
    pub const C_BaseEntity_CheckPredictionForceReLatch: &str = "48 8B C4 48 89 50 10 53 55 56 48 81 EC 00 01 00";
    pub const C_BaseEntity_ProcessInterpolatedList: &str = "4C 8B DC 49 89 5B 10 49 89 6B 18 49 89 73 20 57 41 54 41 57";
    pub const C_BaseEntity_RestoreData: &str = "40 55 53 56 41 54 41 57 48 8D AC 24 20 FF FF FF";
    pub const C_BaseEntity_SaveData: &str = "48 8B C4 55 56 57 41 56 41 57 48 8D A8 E8 FD FF";
    pub const C_BaseModelEntity: &str = "40 55 41 56 48 83 EC 78 4C 8B F2 83 F9 06 0F 87 ? ? ? ? 48 63 C1 48 8D 15 D2 7F";
    pub const C_BasePlayerPawn: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
    pub const C_C4: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
    pub const C_CSPlayerPawn: &str = "40 56 48 83 EC 40 48 8B F2 83 F9 06 0F 87 85 01";
    pub const C_CSPlayerPawnBase: &str = "40 53 48 83 EC 20 65 48 8B 04 25 58 00 00 00 8B 0D 3B D4 96";
    pub const C_CSWeaponBase: &str = "40 56 48 83 EC 40 48 8B F2 85 C9 74 27 83 F9 06 74 08 33 C0 48 83 C4 40 5E C3 48 8B 02 48 8B CE 48 8D 54 24 68 FF 90 70 01 00 00 48 8B 00 48 83";
    pub const C_CSWeaponBase_GetEconWpnData: &str = "40 53 48 83 EC 40 48 8B D9 E8 ? ? ? ? 48 8B C8 E8 FA 52";
    pub const C_EconEntity_BuildLegacyGloveSkinMaterial: &str = "40 55 56 57 48 8D AC 24 30 FD FF FF 48 81 EC D0";
    pub const C_EconEntity_BuildLegacyWeaponSkinMaterial: &str = "40 55 53 41 57 48 8D AC 24 00 FE FF FF 48 81 EC";
    pub const C_EconEntity_BuildModernWeaponSkinMaterial: &str = "48 85 C9 0F 84 ? ? ? ? 48 8B C4 48 89 50 10";
    pub const C_EconEntity_BuildNametagOverlayMaterial: &str = "40 55 53 56 48 8D AC 24 B0 FC FF FF 48 81 EC 50";
    pub const C_EconItemView: &str = "40 56 48 83 EC 20 48 8B F2 85 C9 74 27 83 F9 06";
    pub const C_EconWearable_OnNewCustomMaterials: &str = "48 89 5C 24 08 57 48 83 EC 20 8B DA 48 8B F9 E8 ? ? ? ? F6 C3 01 0F";
    pub const C_Hostage: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
    pub const C_Inferno: &str = "48 89 5C 24 10 48 89 74 24 18 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
    pub const C_PlantedC4: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
    pub const C_SmokeGrenadeProjectile: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
    pub const CacheParticleEffect: &str = "4C 8B DC 53 48 81 EC 90 00 00 00 F2 0F 10 05 65";
    pub const CalcSpread: &str = "48 8B C4 48 89 58 08 48 89 68 18 48 89 70 20 57 41 54 41 55 41 56 41 57 48 81 EC E0";
    pub const CalcViewmodel: &str = "40 55 53 56 41 56 41 57 48 8B EC 48 83 EC 20 4D";
    pub const CalcViewmodelTransform_v2: &str = "48 89 5C 24 20 55 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 80 48 81 EC 80 01 00 00 48 8B FA 48";
    pub const CalcViewmodelView: &str = "40 53 48 83 EC 60 48 8B 41 08 49 8B D8 8B 48 30";
    pub const CalculateInterpolation: &str = "48 83 EC 08 4C 8B 0D ? ? ? ? 4C 8B DA 48 8B";
    pub const CalculateWorldSpaceBones: &str = "48 89 4C 24 08 55 53 56 57 41 54 41 55 41 56 41 57 B8 58 42";
    pub const ClearHUDWeaponIcon: &str = "4C 8B DC 55 57 48 83 EC 48 48 63 41 68 48 8B F9";
    pub const ClientModeCSNormal_OnEvent: &str = "40 53 57 48 81 EC 78 02 00 00 48 8B CA 48 8B FA";
    pub const ClientMode_ptr: &str = "48 8D 0D ? ? ? ? 48 69 C0 ? ? ? ? 48 03 C1 C3 CC CC";
    pub const Client_DispatchSpawn: &str = "4C 8B DC 55 56 48 83 EC 78 49 8B 68 08 48 8B F1";
    pub const CompositeMaterialPanoramaPanel_Init: &str = "48 8B C4 4C 89 40 18 55 56 41 56 48 8D 68 A1 48";
    pub const ComputeRandomSeed: &str = "48 89 5C 24 08 57 48 81 EC F0 00 00 00 F3 0F 10";
    pub const ConCommand_firstperson: &str = "48 83 EC 28 48 8B 0D ? ? ? ? 48 8D 54 24 30 48 8B 01 FF 90 08 03 00 00 83 7C 24 30 00 75 69";
    pub const ConCommand_thirdperson: &str = "48 83 EC 38 48 8B 0D ? ? ? ? 48 8D 54 24 40";
    pub const ConvarGet: &str = "8B D0 48 8D 0D ? ? ? ? E8 ? ? ? ? 0F 10 45 D0 83 F0";
    pub const CreateBaseTypeCache: &str = "40 53 48 83 EC 20 4C 8B 49 18 44 8B D2 4C 63 41";
    pub const CreateEntityByClassName: &str = "4C 8D 05 ? ? ? ? 4C 8B CF BA 03 00 00 00 FF 15 55 0B 30";
    pub const CreateInterface: &str = "4C 8B 0D ? ? ? ? 4C 8B D2 4C 8B D9 4D 85 C9";
    pub const CreateNewSubtickMoveStep: &str = "48 89 5C 24 10 57 48 83 EC 20 33 DB 48 8B F9 48 85 C9 75 2D B9 38 00 00 00 E8 E2 DA";
    pub const CreateParticleEffect: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 50 F3 0F 10 1D 21";
    pub const CreateSOSubclassEconItem: &str = "48 83 EC 28 B9 48 00 00 00 E8 ? ? ? ? 48 85";
    pub const DamageFeedbackEmitter: &str = "48 89 4C 24 08 55 53 41 54 41 55 41 57 48 8D AC";
    pub const DestroyParticle: &str = "83 FA FF 0F 84 ? ? ? ? 41 54 41 56 41 57 48";
    pub const DispatchEffect: &str = "48 89 5C 24 08 57 48 83 EC 70 48 8B F9 48 8B DA";
    pub const DispatchSpawn_caller: &str = "4C 8B DC 55 56 48 83 EC 78 49 8B 68 08 48 8B F1";
    pub const DrawCrosshair: &str = "48 89 5C 24 08 57 48 83 EC 20 48 8B D9 E8 AE AC";
    pub const DrawLegs: &str = "40 55 53 56 41 56 41 57 48 8D AC 24 A0 FB FF FF";
    pub const DrawOverHead: &str = "40 53 48 83 EC 20 48 8B D9 83 FA FF 75 17 48 8B";
    pub const DrawScopeOverlay: &str = "48 8B C4 53 57 48 83 EC 68 48 8B FA 44 0F 29 40";
    pub const DrawSmokeVertex: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 83 EC 40 48 8B 9C 24 88 00 00 00 4D 8B F8 48 8B FA 48 8B";
    pub const EmitSoundByHandle: &str = "40 53 48 83 EC 30 4C 89 4C 24 20 48 8B D9 45 8B";
    pub const FX_FireBullets: &str = "48 8B C4 4C 89 48 20 48 89 50 10 55 53 57 41 54";
    pub const FX_FireBullets: &str = "48 8B C4 4C 89 48 20 48 89 50 10 55 53 57 41 54";
    pub const FindHudElement: &str = "48 8D 15 ? ? ? ? 45 33 C0 B9 01 00 00 00 FF 15 23 2C B4";
    pub const FindHudElement_panorama: &str = "4C 8B DC 53 48 83 EC 50 48 8B 05 ? ? ? ? 48";
    pub const FindSOCache: &str = "48 89 5C 24 08 57 48 83 EC 30 4C 8B 52 08 48 8B";
    pub const FirstPersonLegs: &str = "40 55 53 56 41 56 41 57 48 8D AC 24 A0 FB FF FF";
    pub const FlashOverlay: &str = "85 D2 0F 88 ? ? ? ? 48 89 4C 24 08 55 53 41";
    pub const ForceButtonsDown: &str = "40 53 57 41 56 48 81 EC 30 02 00 00 48 83 79 38";
    pub const GameEntitySystemPtr: &str = "48 8B 1D ? ? ? ? 48 89 1D ? ? ? ?";
    pub const GameEventManager_AddListener: &str = "48 89 5C 24 10 48 89 6C 24 18 56 57 41 56 48 83 EC 50 41 0F";
    pub const GameEventManager_UnserializeEvent: &str = "48 8B C4 48 89 50 10 55 41 54 41 55 41 56 48 8D";
    pub const GameRules_ptr: &str = "48 8B 1D ? ? ? ? 48 8D 54 24 ? 0F 28 D0 48 8D 4C 24 ?";
    pub const GetBBox_ptr: &str = "48 8B 0D ? ? ? ? 48 85 C9 74 ? ? ? ? 48 FF A0 ? ? ? ? 48 8D 05";
    pub const GetBaseEntity: &str = "4C 8D 49 10 81 FA FE 7F 00 00 77 47 8B CA C1 F9";
    pub const GetBonePositionByName: &str = "40 53 48 83 EC 20 48 8B 89 30 03 00 00 48 8B DA 48 8B 01 FF 50 50 48 8B";
    pub const GetChatObject: &str = "48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 8B 05 ? ? ? ? 48";
    pub const GetClientSystem: &str = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 30 48";
    pub const GetControllerCmd: &str = "40 53 48 83 EC 20 8B DA E8 ? ? ? ? 4C 8B C0";
    pub const GetEconItemSystem: &str = "48 83 EC 28 48 8B 05 ? ? ? ? 48 85 C0 0F 85 ? ? ? ? 48 89 5C 24 30 B9 50 00 00 00 48 89 74 24 40 4C 89 74 24 20 E8 ? ? ? ? 33 F6 48";
    pub const GetEntityByIndex: &str = "4C 8D 49 10 81 FA FE 7F 00 00 77 47 8B CA C1 F9";
    pub const GetEntityHandle: &str = "48 85 C9 74 32 48 8B 49 10 48 85 C9 74 29 44 8B";
    pub const GetGlowColor: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 48 8B F2 48 8B F9 48 8B";
    pub const GetHitGroup: &str = "40 53 48 83 EC 20 48 83 79 10 00 48 8B D9 74 16";
    pub const GetInstanceS: &str = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 8B 91 ? ? ? ? B8";
    pub const GetInt2_Event: &str = "48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 20 48 63 FA 41 8B F0 4C 8B F1 45 85 C0 74 79 8B 41 10 48 89 5C 24 30 8B 19 41 03 D8 4C 89 7C 24 38";
    pub const GetInventoryManager: &str = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 0F B6 81 6B";
    pub const GetLocalControllerById: &str = "48 83 EC 28 83 F9 FF 75 17 48 8B 0D ? ? ? ? 48 8D 54 24 30 48 8B 01 FF 90 08 03 00 00 8B 08 48 63 C1 4C 8D 05 36 A5";
    pub const GetLocalPawn: &str = "48 83 EC 28 83 F9 FF 75 17 48 8B 0D ? ? ? ? 48 8D 54 24 30 48 8B 01 FF 90 08 03 00 00 8B 08 48 63 C1 4C 8D 05 36 A5";
    pub const GetLocalPlayer_dispatcher: &str = "48 83 EC 38 48 8B 05 ? ? ? ? 48 85 C0 0F 85 ? ? ? ? 48 89 5C 24 40 B9 50 00 00 00 48 89 74 24 50 4C 89 74 24 28 4C 89 7C 24 20 E8 4E 66";
    pub const GetMatrixForView: &str = "40 53 48 83 EC 60 0F 29 74 24 50 0F 57 DB F3 0F";
    pub const GetPlayerByIndex_export: &str = "48 83 EC 28 4C 8D 05 ? ? ? ? 48 8D 15 0E DF";
    pub const GetPlayerInterp: &str = "40 53 48 83 EC 20 48 8B D9 48 8B 0D ? ? ? ? 48 83 C1 08";
    pub const GetRemovedAimPunch_E8: &str = "40 53 48 83 EC 20 48 8B 89 90 14 00 00 48 8B DA";
    pub const GetRemovedAimpunch: &str = "F2 0F 10 44 24 60 F2 0F 11 84 24 88 00 00 00 FF 15 8C 30 7F";
    pub const GetSurfaceData: &str = "48 63 41 10 48 8B 0D ? ? ? ? 48 C1 E0 05 48";
    pub const GetTickBase: &str = "8B 81 B8 06 00 00 C3 CC CC CC CC CC CC CC CC CC";
    pub const GetTraceInfo: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 60 48 8B E9 0F";
    pub const GetUserCmdManager: &str = "41 56 41 57 48 83 EC 48 48 8D 54 24 68 E8 CE A1";
    pub const GetViewAngles: &str = "4C 8B C1 85 D2 74 08 48 8D 05 ? ? ? ? C3 8B";
    pub const GetWeaponInAccuracyRecoveryTime: &str = "48 89 5C 24 08 57 48 83 EC 30 48 8B D9 E8 9E 52";
    pub const GetWorldFovResolver: &str = "40 53 48 83 EC 50 48 8B D9 E8 ? ? ? ? 48 85";
    pub const GlobalLightUpdateState: &str = "40 57 48 81 EC C0 00 00 00 48 8B F9 BA FF FF FF";
    pub const GlobalVariables_ptr: &str = "48 89 15 ? ? ? ? 48 89 42";
    pub const GloveApply_PerTick: &str = "40 55 56 57 48 8D AC 24 30 FD FF FF 48 81 EC D0";
    pub const GlowManager_ptr: &str = "48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 8B 41";
    pub const GlowObjectManager_GetInstance: &str = "48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 8B 41 38 C3";
    pub const HandleBulletPenetration: &str = "48 8B C4 44 89 48 20 48 89 50 10 48 89 48 08 55 57 41 57 48";
    pub const HandleEntityList: &str = "48 8B C4 4C 89 48 20 4C 89 40 18 48 89 50 10 55 56 41 57 48";
    pub const HandleTeamIntro: &str = "48 83 EC 28 45 0F B6 08 44 38 89 04 0F 00 00 74";
    pub const HudChatPrintf: &str = "4C 89 44 24 18 4C 89 4C 24 20 53 B8 40 10 00 00";
    pub const InfoForResourceTypeCCompositeMaterialKit_TypeManager: &str = "40 55 41 56 48 83 EC 78 4C 8B F2 83 F9 06 0F 87 ? ? ? ? 48 63 C1 48 8D 15 32 6F";
    pub const InfoForResourceTypeCCompositeMaterial_TypeManager: &str = "40 55 41 56 48 83 EC 68 48 8B EA 83 F9 06 0F 87 ? ? ? ? 48 63 C1 48 8D 15 E2 69";
    pub const InitFilter: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 0F B6 41 39 33 FF 24 C9 C7";
    pub const InitPlayerMovementTraceFilter: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 0F B6 41 39 33 FF C7 41 34";
    pub const InitTraceInfo: &str = "40 55 41 55 41 57 48 83 EC 30 4C 8B 3D 6F CC EE";
    pub const IsGlowing: &str = "0F B6 41 51 C3 CC CC CC CC CC CC CC CC CC CC CC";
    pub const KillFeedbackEmitter: &str = "48 89 5C 24 08 48 89 74 24 18 48 89 7C 24 20 55 41 56 41 57 48 8B EC 48 81 EC 80 00";
    pub const LevelInit: &str = "40 55 56 41 56 48 8D 6C 24 90 48 81 EC 70 01 00";
    pub const LoadFileForMe: &str = "40 55 57 41 56 48 83 EC 20 4C 63 71 18 33 FF 48";
    pub const LoadPath: &str = "48 89 74 24 20 57 48 83 EC 20 44 8B 49 04 BF FF FF FF 7F 44 23 CF 48 8B F1 41 8B C8 45 85 C0 74 30 83 E9 ? ? ? ? F9 01 0F 85 ? ? ? ? 41";
    pub const LocalPlayerController_ptr: &str = "48 8B 05 ? ? ? ? 41 89 BE";
    pub const LookupBone: &str = "40 53 48 83 EC 20 48 8B 89 30 03 00 00 48 8B DA 48 8B 01 FF 50 50 48 8B";
    pub const ModulationUpdate: &str = "48 89 5C 24 08 57 48 83 EC 20 8B FA 48 8B D9 E8 ? ? ? ? 84 C0 0F 84";
    pub const NoClipOnChange: &str = "48 89 5C 24 10 48 89 74 24 18 48 89 7C 24 20 55 48 8B EC 48 83 EC 30 48 8D 05 AA 1A";
    pub const NoSpread1: &str = "48 89 5C 24 08 57 48 81 EC F0 00 00 00 F3 0F 10";
    pub const ParticleCollection: &str = "48 89 5C 24 08 57 48 83 EC 20 0F 28 05 AF 37 2E";
    pub const ParticleManager_ptr: &str = "48 8B 0D ? ? ? ? 41 B8 ? ? ? ? F3 0F 11 74 24 ? 48 C7 44 24 ? ? ? ? ?";
    pub const PhysicsRunThink_Ctrl: &str = "48 89 5C 24 20 57 48 81 EC D0 06 00 00 48 8B 01";
    pub const PhysicsRunThink_Pawn: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 8B 81 74 03 00";
    pub const PlayVSound_client: &str = "48 89 5C 24 08 48 89 74 24 18 48 89 7C 24 20 55 48 8D 6C 24 A9 48 81 EC 90 00 00 00";
    pub const Prediction_ptr: &str = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 40 53 56 41 54";
    pub const ProcessImpacts: &str = "48 8B C4 53 56 41 55 48 81 EC E0 00 00 00 44 0F";
    pub const ProcessMovement: &str = "48 8B C4 53 55 56 57 41 54 41 55 41 56 41 57 48 83 EC 78 44";
    pub const RegenerateWeaponSkin: &str = "40 55 53 41 57 48 8D AC 24 00 FE FF FF 48 81 EC";
    pub const RegenerateWeaponSkin_v2: &str = "40 55 53 41 57 48 8D AC 24 00 FE FF FF 48 81 EC";
    pub const RegenerateWeaponSkins: &str = "48 83 EC 48 E8 ? ? ? ? 48 85 C0 0F 84 7F 00";
    pub const RenderDecals: &str = "44 88 4C 24 20 55 53 57 41 54 41 55 48 8D 6C 24";
    pub const ReportHit: &str = "40 53 48 83 EC 20 48 8D 05 ? ? ? ? 48 8D 59 08 48 89 01 F6 03 01 74 08 48 8B CB E8 AF FB EA";
    pub const RunCommand: &str = "48 8B C4 48 81 EC C8 00 00 00 48 89 58 10 48 89";
    pub const RunCommand_processor: &str = "48 8B C4 48 81 EC C8 00 00 00 48 89 58 10 48 89";
    pub const Scope_callsite: &str = "48 8B C4 53 57 48 83 EC 68 48 8B FA 44 0F 29 40";
    pub const SendChatMessage: &str = "4C 89 44 24 18 4C 89 4C 24 20 53 B8 40 10 00 00";
    pub const Sensitivity_ptr: &str = "48 8D 0D ? ? ? ? 66 0F 6E CD";
    pub const SetAbsOrigin_Pawn: &str = "48 89 5C 24 08 57 48 83 EC 60 48 8B 01 48 8B FA 48 8B D9 FF";
    pub const SetBodyGroup_inv: &str = "85 D2 0F 88 ? ? ? ? 53 55 48 83 EC 38 48 63";
    pub const SetCollisionBounds: &str = "48 83 EC 38 F2 0F 10 02 8B 42 08 48 8D 54 24 20";
    pub const SetDynamicAttributeValue: &str = "48 89 6C 24 20 57 41 56 41 57 48 81 EC A0 00 00 00 48 8B FA C7 44 24 20 00 00 00 00 4D 8B F8 4C 8D 0D ? ? ? ? 48 8B E9 ? ? ? ? CD 12 01";
    pub const SetDynamicAttributeValue_raw: &str = "48 89 6C 24 20 57 41 56 41 57 48 81 EC A0 00 00 00 48 8B FA C7 44 24 20 00 00 00 00 4D 8B F8 4C 8D 0D ? ? ? ? 48 8B E9 ? ? ? ? CD 12 01";
    pub const SetMeshGroupMask: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8D 99 50 01";
    pub const SetModel: &str = "40 53 48 83 EC 20 48 8B D9 4C 8B C2 48 8B 0D ED";
    pub const SetPlayerReady: &str = "40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ? ? 48 8B CB FF";
    pub const SetPlayerReady: &str = "40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ? ? 48 8B CB FF";
    pub const SetTraceData: &str = "48 89 6C 24 18 48 89 7C 24 20 41 56 48 83 EC 20 48 63 29 4C 8B F2 48 8B F9 3B 69 10 0F 85 ? ? ? ? F7 41 14 00 00 00 40 0F 85 ? ? ? ? 8B";
    pub const SetTypeKV3: &str = "40 53 48 83 EC 30 4C 8B 11 41 B9 16 00 00 00 49";
    pub const SetViewAngle: &str = "85 D2 75 3D 48 63 81 50 0B 00 00 F2 41 0F 10 00";
    pub const SetupCmd: &str = "48 83 EC 28 E8 ? ? ? ? 8B 80 10 59 00 00 48";
    pub const SetupMove: &str = "48 89 5C 24 18 48 89 6C 24 20 56 57 41 56 48 83 EC 20 48 8B EA 4C 8B F1";
    pub const SetupMovementMoves: &str = "48 8B CE E8 ? ? ? ? 48 8B 5C 24 50 48 8B 6C 24 58 48 83";
    pub const ShowMessageBox: &str = "44 88 4C 24 20 53 41 56 41 57 48 81 EC 60 02 00";
    pub const SomeTimingFromPawn: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 49 63 D8 48 8B";
    pub const Spawner_PerTickOrchestrator: &str = "48 8B C4 55 53 48 8D A8 E8 ? ? ? ? 81 EC 08";
    pub const SpectatorInput: &str = "48 89 5C 24 10 55 56 57 41 56 41 57 48 8B EC 48 83 EC 60 48";
    pub const SpreadSeedGen: &str = "48 89 5C 24 08 57 48 81 EC F0 00 00 00 F3 0F 10";
    pub const TestSurfaces: &str = "40 53 57 41 56 48 83 EC 50 8B 84 24 90 00 00 00";
    pub const ThirdPersonOffHandler: &str = "48 83 EC 28 48 8B 0D ? ? ? ? 48 8D 54 24 30 48 8B 01 FF 90 08 03 00 00 83 7C 24 30 00 75 69";
    pub const ThirdPersonOnHandler: &str = "48 83 EC 38 48 8B 0D ? ? ? ? 48 8D 54 24 40";
    pub const TraceCreate: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 83 EC 50 F2 0F 10 02";
    pub const TraceGetInfo: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 60 48 8B E9 0F";
    pub const TraceHandleBulletPen: &str = "48 8B C4 44 89 48 20 48 89 50 10 48 89 48 08 55 57 41 57 48";
    pub const TraceInitData: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8D 79 08 33";
    pub const TraceInitFilter: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 0F B6 41 39 33 FF 24 C9 C7";
    pub const TraceInitInfo: &str = "40 55 41 55 41 57 48 83 EC 30 4C 8B 3D 6F CC EE";
    pub const TracePlayerBBox: &str = "48 89 5C 24 18 55 57 41 54 41 55 41 56 48 8D 6C";
    pub const TraceShape: &str = "48 89 5C 24 20 48 89 4C 24 08 55 57 41 54 41 55";
    pub const TraceShape_Client: &str = "48 89 5C 24 20 48 89 4C 24 08 55 57 41 54 41 55";
    pub const TraceToExit: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 83 EC 50 F2 0F 10 02";
    pub const UpdateGlobalVars: &str = "48 8B 0D ? ? ? ? 4C 8D 05 ? ? ? ? 48 85 D2 48 8D 05";
    pub const UpdatePostProcessing: &str = "48 85 D2 0F 84 ? ? ? ? 48 89 5C 24 08 57 48 83 EC 60 80";
    pub const UpdatePostProcessing: &str = "48 85 D2 0F 84 ? ? ? ? 48 89 5C 24 08 57 48 83 EC 60 80";
    pub const UpdateSkybox: &str = "48 89 5C 24 08 57 48 83 EC 30 48 8B F9 E8 8E F1";
    pub const UpdateSubClass: &str = "48 8B 41 10 48 8B D9 8B 50 30 C1 EA 04 F6 C2 01";
    pub const UpdateTurningInAccuracy: &str = "40 56 48 81 EC 80 00 00 00 48 8B F1 BA FF FF FF";
    pub const VPhys2World_ptr: &str = "4C 8B 25 ? ? ? ? 24";
    pub const ViewModelHideZoomed: &str = "48 89 5C 24 20 55 56 57 41 54 41 56 48 8B EC 48 83 EC 50 48 8D 05 86 01";
    pub const ViewRender_ptr: &str = "48 89 05 ? ? ? ? 48 8B C8 48 85 C0";
    pub const WeaponC4_ptr: &str = "48 8B 15 ? ? ? ? 48 8B 5C 24 ? FF C0 89 05 ? ? ? ? 48 8B C6 48 89 34 EA 80 BE";
    pub const WriteSubtickFromEntry: &str = "48 89 5C 24 18 55 57 41 56 48 8D 6C 24 C9 48 81";
    pub const create_move_v2: &str = "85 D2 0F 85 ? ? ? ? 48 8B C4 44 88 40 18 89";
    pub const draw_smoke_array: &str = "40 55 41 54 41 55 48 8D AC 24 20 F9 FF FF 48 81";
    pub const draw_view_punch_v2: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 40 49 8B E9 49 8B F8";
    pub const entity_list_ptr: &str = "48 8B 1D ? ? ? ? 48 8D 46";
    pub const frame_stage_notify: &str = "4C 8B 0D ? ? ? ? 48 8D 15 ? ? ? ? 48 8B 8F 38 04 00";
    pub const get_fov: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 40 49 8B E9 49 8B F8";
    pub const get_map_name: &str = "48 83 EC 28 48 8B 0D ? ? ? ? 48 8B 01 FF 90 00 02 00 00";
    pub const get_view_angles_v2: &str = "4D 85 C0 74 72 85 D2 74 18 48 8D 05 ? ? ? ?";
    pub const get_view_model: &str = "40 55 53 56 41 56 41 57 48 8B EC 48 83 EC 20 4D";
    pub const global_vars_v2: &str = "48 89 1D ? ? ? ? FF 15 ? ? ? ? 84 C0 74 ? 8B 0D ? ? ? ? 4C 8D 0D ? ? ? ? 4C 8D 05 ? ? ? ? BA ? ? ? ? FF 15 ? ? ? ? 48 8B 74 24 ? 48 8B C3";
    pub const is_demo_or_hltv: &str = "48 83 EC 28 48 8B 0D ? ? ? ? 48 8B 01 FF 90 50 01 00 00 84 C0 75 0D";
    pub const level_init_v2: &str = "40 55 56 41 56 48 8D 6C 24 B9 48 81 EC E0 00 00 00 48 8B 0D";
    pub const level_shutdown: &str = "48 83 EC 28 48 8B 0D ? ? ? ? 48 8D 15 66 C4";
    pub const local_controller: &str = "48 8B 05 ? ? ? ? 41 89 BE";
    pub const mark_interp_latch_flags_dirty: &str = "40 53 56 57 48 83 EC 40 80 3D A1 97 10 02 00 8B";
    pub const on_add_entity_v2: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 8B 81 C0 20";
    pub const override_view_short: &str = "40 57 48 83 EC 60 48 8B FA E8 ? ? ? ? BA FF";
    pub const paintkit_prefab: &str = "48 89 5C 24 10 48 89 6C 24 18 48 89 74 24 20 57 48 83 EC 30 48 8B D9 48 81 C1 80 11";
    pub const paintkit_seed: &str = "48 89 4C 24 08 53 56 57 41 54 41 55 41 56 41 57 48 83 EC 50 65 48 8B 04";
    pub const paintkit_wear: &str = "48 89 4C 24 08 53 56 57 41 54 41 55 41 56 41 57 48 83 EC 50 65 48 8B 04";
    pub const planted_c4_ptr: &str = "48 8B 15 ? ? ? ? 48 8B 5C 24 ? FF C0 89 05 ? ? ? ? 48 8B C6 ? ? ? ? 80 BE ? ? ? ? 00";
    pub const remove_legs: &str = "40 55 53 56 41 56 41 57 48 8D AC 24 A0 FB FF FF";
    pub const statTrak_killEater: &str = "48 89 4C 24 08 53 56 57 41 54 41 55 41 56 41 57 48 83 EC 50 65 48 8B 04";
    pub const statTrak_scoreType: &str = "48 83 EC 28 E8 ? ? ? ? 48 8B 15 ? ? ? ? 48 8B 48 08";
    pub const unlock_inventory: &str = "48 89 5C 24 08 48 89 6C 24 18 48 89 74 24 20 57 48 83 EC 20 48 8B E9 48";
    pub const update_global_vars: &str = "48 8B 0D ? ? ? ? 4C 8D 05 ? ? ? ? 48 85 D2 48 8D 05";
    pub const update_post_processing_v2: &str = "48 89 AC 24 B8 00 00 00 45 33 ED 0F 29 74 24 70";
    pub const view_matrix_ptr: &str = "48 8D 0D ? ? ? ? 48 89 44 24 ? 48 89 4C 24 ? 4C 8D 0D";
}

pub mod engine2 {
    pub const BuildNumber_addr: &str = "89 05 ? ? ? ? 48 8D 0D ? ? ? ? FF 15 ? ? ? ? 48 8B 0D";
    pub const CCommand_Tokenize: &str = "48 89 6C 24 20 4C 89 44 24 18 56 57 41 54 41 56";
    pub const CGameClient_ClientCommand: &str = "48 8B C4 4C 89 40 18 4C 89 48 20 55 53 57 48 8D";
    pub const CHLTVClient_ExecuteStringCommand: &str = "40 53 56 48 81 EC 48 07 00 00 48 8B F1 48 8B DA";
    pub const CNetworkGameClientBase_ForceDemoRecordingFullUpdateAfterNextDeltaPacket: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8B 1D FA 0D";
    pub const CNetworkGameClient_ProcessTick: &str = "48 89 5C 24 20 55 57 41 57 48 81 EC F0 00 00 00";
    pub const CServerSideClient_ExecuteStringCommand: &str = "40 55 53 56 48 8D AC 24 50 FA FF FF 48 81 EC B0";
    pub const CSplitScreenSlot: &str = "48 83 EC 58 4C 8B D2 45 85 C0 0F 85 ? ? ? ?";
    pub const Cvar_RegisterConCommand: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 60 44 8B 15 89";
    pub const Cvar_RegisterConVar: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 54 41 56 41 57 48 81 EC D0 00 00";
    pub const Cvar_RevertFlaggedCvars_OnSvCheatsChange: &str = "40 53 48 83 EC 20 48 8B 41 08 48 8B D9 8B 50 30";
    pub const DisablePvsAccessor: &str = "48 8D 0D ? ? ? ? 33 D2 FF 50 30 48 8B CF C7";
    pub const Engine__GetScreenAspectRatio: &str = "48 89 5C 24 08 57 48 83 EC 20 8B FA 48 8D 0D 0D";
    pub const Engine__PVSManager_ptr: &str = "48 8D 0D ? ? ? ? 33 D2 FF 50";
    pub const Engine__RunPrediction: &str = "40 55 41 56 48 83 EC 68 80 B9 00 01 00 00 00 8B";
    pub const Engine_Disconnect_main: &str = "48 89 5C 24 20 55 57 41 54 48 8B EC 48 83 EC 70";
    pub const Engine_HLTVClient_ExecuteStringCommand: &str = "40 53 56 48 81 EC 48 07 00 00 48 8B F1 48 8B DA";
    pub const Engine_HostStateMgr_QueueNewRequest: &str = "48 89 6C 24 18 48 89 7C 24 20 41 56 48 83 EC 30 48 8B EA 48";
    pub const Engine_HostStateMgr_QueueNewRequest: &str = "48 89 6C 24 18 48 89 7C 24 20 41 56 48 83 EC 30 48 8B EA 48";
    pub const Engine_LoadGameInfo: &str = "40 55 56 41 56 48 8D 6C 24 F0 48 81 EC 10 01 00";
    pub const Engine_MountAddon: &str = "48 85 D2 0F 84 ? ? ? ? 48 8B C4 44 88 40 18";
    pub const Engine_NetTimeoutDisconnect: &str = "40 53 55 56 57 41 56 48 81 EC 80 00 00 00 0F 29";
    pub const Engine_NetworkGameClient_Connect: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 40 44 89 81 3C";
    pub const Engine_NetworkGameClient_SetSignonState: &str = "44 89 44 24 18 89 54 24 10 55 53 56 57 41 55 41";
    pub const Engine_RegisterConCommand: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 60 44 8B 15 89";
    pub const Engine_RegisterConVar: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 54 41 56 41 57 48 81 EC D0 00 00";
    pub const IsInGame: &str = "48 8B 05 ? ? ? ? 48 85 C0 74 15 80 B8 1F 14";
    pub const NetworkGameClient_ptr: &str = "48 89 3D ? ? ? ? FF 87";
    pub const WindowHeight_addr: &str = "8B 05 ? ? ? ? 89 03";
    pub const WindowWidth_addr: &str = "8B 05 ? ? ? ? 89 07";
}

pub mod filesystem_stdio {
    pub const FullFileSystem_ptr: &str = "8B 41 28 C3 CC CC CC CC CC CC CC CC CC CC CC CC 48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 8D 05 ? ? ? ? C3";
}

pub mod inputsystem {
    pub const InputSystemSvc_ptr: &str = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 40 53 48 83 EC 20 33 DB";
    pub const InputSystem_ptr: &str = "48 89 05 ? ? ? ? 33 C0";
}

pub mod matchmaking {
    pub const GameTypes_ptr: &str = "48 8D 0D ? ? ? ? FF 90";
}

pub mod materialsystem2 {
    pub const CMaterial2_CompileComboAndGetVariables_DynamicShaderCompile: &str = "48 89 54 24 10 55 41 55 48 8D 6C 24 F8 48 81 EC";
    pub const CMaterial2_GetMode: &str = "48 89 5C 24 18 57 48 83 EC 30 8B 02 48 8B D9 39";
    pub const CMaterial2_GetVertexShaderInputSignature: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 30 F6 41";
    pub const CMaterial2_GetVertexShaderInputSignature: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 30 F6 41";
    pub const CMaterial2_LoadShadersAndSetupModes: &str = "44 89 44 24 18 48 89 54 24 10 53 56 41 54 41 55";
    pub const CMaterialLayer_ApplyMaterialVarsForBatch: &str = "4C 89 4C 24 20 4C 89 44 24 18 48 89 54 24 10 53";
    pub const CMaterialLayer_BuildPassCommandData: &str = "89 54 24 10 55 53 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 58 FE FF FF";
    pub const CMaterialLayer_ComputeWorkItemsToSetupStaticCombosForMode: &str = "48 8B CF 88 44 24 20 49 8B D2 E8 ? ? ? ? 84";
    pub const CMaterialLayer_CreateCommandBuffer: &str = "4C 8B DC 45 89 4B 20 45 89 43 18 49 89 53 10 49";
    pub const CMaterialSystem2_BindIdentityInstanceIDBufferAndSetRenderState: &str = "40 55 41 54 41 55 41 57 48 8D AC 24 98 FD FF FF";
    pub const CMaterialSystem2_DynamicShaderCompile_ProcessQueue: &str = "48 83 39 00 74 06 FF 15 E4 53 0B 00 44 8B C7 45";
    pub const CMaterialSystem2_DynamicShaderCompile_ReloadAndSync: &str = "48 83 EC 20 48 8B 35 ? ? ? ? 48 8B CE E8 CB";
    pub const CMaterialSystem2_DynamicShaderCompile_UnloadAllMaterials: &str = "48 8B C4 41 57 48 81 EC B0 00 00 00 F6 81 80 05";
    pub const CMaterialSystem2_FrameUpdate: &str = "48 89 4C 24 08 55 53 56 57 41 54 41 56 48 8B EC";
    pub const CMaterialSystem2_GetErrorMaterial: &str = "48 8B 05 ? ? ? ? 48 8B 48 30 48 85 C9 75 31";
    pub const CMaterialSystem2_Init: &str = "40 55 53 41 55 41 56 41 57 48 8D AC 24 20 FF FF";
    pub const CMaterial_SetVariableAndRenderState: &str = "48 89 5C 24 08 4C 89 44 24 18 48 89 54 24 10 55 56 57 41 54 41 55 41 56 41 57 48 8B EC 48 83 EC 70 4C 8B BD 90 00 00 00";
    pub const CVfxProgramData_FindOrCreateStaticComboDataInCache: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 54 41 55 41 56 41 57 48 83 EC 20 33 ED 4C 8B";
    pub const CVfxProgramData_FindOrCreateStaticComboData_CacheGate: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 57 48 83";
    pub const CVfxProgramData_FindOrLoadStaticComboData: &str = "4C 89 4C 24 20 48 89 54 24 10 48 89 4C 24 08 55";
    pub const FindParameter: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8B 59 20 48";
    pub const MatSys__PrepareSceneMaterial: &str = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 30 48 8B 59 20 48";
    pub const UpdateParameter: &str = "48 89 7C 24 20 41 56 48 83 EC 20 8B 81 14 04 00";
}

pub mod networksystem {
    pub const CNetChan_ProcessMessages: &str = "48 8B C4 53 57 41 54 41 56 48 81 EC A8 00 00 00";
    pub const CNetChan_SendNetMessage: &str = "48 89 5C 24 10 48 89 6C 24 18 56 57 41 56 48 83 EC 40 41 0F";
    pub const CNetworkSystem_Init: &str = "40 55 53 57 41 54 41 55 41 57 48 8D AC 24 98 FC";
    pub const CNetworkSystem_RegisterNetMessageHandlerAbstract: &str = "48 89 5C 24 10 48 89 6C 24 18 57 41 56 41 57 48 83 EC 50 4C";
    pub const NetSystem_CNetChan_ProcessMessages: &str = "48 8B C4 53 57 41 54 41 56 48 81 EC A8 00 00 00";
    pub const NetSystem_CNetChan_SendNetMessage: &str = "48 89 5C 24 10 48 89 6C 24 18 56 57 41 56 48 83 EC 40 41 0F";
    pub const NetworkSystem_ptr: &str = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 83 EC 28 BA FF FF FF";
}

pub mod particles {
    pub const GetParticleManager: &str = "48 8B 05 ? ? ? ? C3 ? ? ? ? ? ? ? ? 48 83 EC 28 8B 0D";
    pub const Particles__CParticleSystemMgr_CreateParticleCollection: &str = "4C 8B DC 49 89 5B 10 49 89 6B 18 49 89 73 20 57 41 56 41 57";
    pub const Particles__CParticleSystemMgr_FindParticleSystem: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 81 EC 40";
    pub const Particles__DrawArray: &str = "40 55 53 56 57 48 8D 6C 24 F8 48 81 EC 08 01 00";
    pub const Particles__FindKeyVar: &str = "48 89 5C 24 08 57 48 81 EC C0 00 00 00 33 C0 8B";
    pub const Particles__SetMaterialShaderType: &str = "48 89 5C 24 10 48 89 6C 24 18 56 57 41 54 41 56 41 57 48 81";
}

pub mod rendersystemdx11 {
    pub const CRenderDeviceBase_CreateConstantBuffer: &str = "48 89 5C 24 08 48 89 74 24 10 48 89 7C 24 18 55 41 56 41 57 48 8D 6C 24";
    pub const CRenderDeviceDx11_BeginSubmittingDisplayLists: &str = "48 89 5C 24 08 57 48 83 EC 50 48 8B F9 48 8B DA";
    pub const CRenderDeviceDx11_CompileShaderSourceMain: &str = "4C 8B DC 49 89 5B 08 57 48 83 EC 70 4D 8B D0 48";
    pub const CSwapChainDx11_QueuePresentAndWait: &str = "40 55 53 57 41 54 41 55 48 8D 6C 24 C9 48 81 EC";
    pub const CSwapChainDx11_ResizeBuffers: &str = "48 8B C4 55 53 56 57 41 54 48 8B EC 48 83 EC 70";
    pub const RenderDeviceMgr_ptr: &str = "8B 5C 24 38 48 83 C4 20 5E C3 CC CC CC CC CC CC 48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 8D 05 ? ? ? ? C3";
    pub const RenderSystemDx11_QueuePresentAndWait: &str = "40 55 53 57 41 54 41 55 48 8D 6C 24 C9 48 81 EC";
    pub const RenderSystemDx11_SetHardwareGammaRamp: &str = "48 89 5C 24 18 57 B8 B0 40 00 00 E8 ? ? ? ?";
    pub const RenderSystemDx11_SetMode: &str = "44 89 4C 24 20 44 89 44 24 18 89 54 24 10 55 53";
}

pub mod resourcesystem {
    pub const ResourceSystem_BlockingLoadResourceByName: &str = "40 53 55 57 48 81 EC 80 00 00 00 48 8B 01 49 8B";
    pub const ResourceSystem_FindOrRegisterResourceByName: &str = "48 89 5C 24 18 48 89 74 24 20 57 48 81 EC A0 00";
    pub const ResourceSystem_FrameUpdate: &str = "44 88 4C 24 20 44 89 44 24 18 89 54 24 10 55 56";
}

pub mod scenesystem {
    pub const BuildSceneInfoGpu: &str = "4C 89 4C 24 20 4C 89 44 24 18 48 89 4C 24 08 55 48 8D AC 24 00 E3 FF FF";
    pub const CSceneAnimatableObject__GeneratePrimitives: &str = "48 8B C4 48 89 58 08 48 89 50 10 55 56 57 41 54 41 55 41 56 41 57 48 81";
    pub const CSceneAnimatableObject_GeneratePrimitives: &str = "48 8B C4 48 89 58 08 48 89 50 10 55 56 57 41 54 41 55 41 56 41 57 48 81";
    pub const CSceneSkyBoxObject_DrawSkyboxArray: &str = "45 85 C9 0F 8E ? ? ? ? 4C 8B DC 55 41 56 49";
    pub const CSceneSystem_CreateStaticShape: &str = "48 8B C4 48 89 48 08 55 41 54 41 56 48 8D 68 D8";
    pub const CSceneSystem_InitGfxObjects: &str = "40 55 53 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 08 FE FF";
    pub const CSceneSystem_RenderViewLayer_Dispatch: &str = "48 8B C4 48 89 48 08 55 53 56 57 41 54 41 55 41 56 41 57 48 8D A8 B8 FE";
    pub const CSceneSystem_Thread_CullView: &str = "4C 89 44 24 18 48 89 54 24 10 48 89 4C 24 08 55 53 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 E1";
    pub const DrawAggregateSceneObjectArray: &str = "48 8B C4 48 89 50 10 48 89 48 08 55 53 56 57 41 54 41 55 41 56 41 57 48 8D A8 38 F9";
    pub const DrawObject_legacy: &str = "48 8B C4 53 57 41 54 48 81 EC D0 00 00 00 49 63";
    pub const DrawSkyboxArray: &str = "45 85 C9 0F 8E ? ? ? ? 4C 8B DC 55 41 56 49";
    pub const SceneSystem__DrawAggeregateObject: &str = "48 8B C4 4C 89 48 20 4C 89 40 18 48 89 50 10 55 53 41 57 48";
    pub const SceneSystem__DrawArrayLight: &str = "48 89 5C 24 08 48 89 6C 24 18 48 89 54 24 10 56 57 41 56 48";
    pub const SceneSystem_Thread_RenderSceneDrawList: &str = "40 55 53 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 E1 48 81 EC D8 00 00";
    pub const SceneSystem_ptr: &str = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 8D 0D ? ? ? ? E9";
}

pub mod schemasystem {
    pub const CSchemaSystem_InstallSchemaBindings: &str = "40 53 48 83 EC 20 48 8B DA 48 8B D1 48 8D 0D 8D";
    pub const CSchemaSystem_RegisterModuleAndBuiltins: &str = "48 89 54 24 10 53 56 57 41 55 41 56 41 57 48 83";
    pub const CSchemaSystem_VerifySchemaBindingConsistency: &str = "88 54 24 10 55 53 57 41 54 41 55 48 8B EC 48 81";
    pub const SchemaSystem_ptr: &str = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 89 5C 24 08 48 89 74";
}

pub mod soundsystem {
    pub const CSosOperatorSystem_StartSoundEvent: &str = "40 53 55 56 48 83 EC 20 83 B9 EC 24 00 00 00 49";
    pub const SoundSystem__PlayVSound: &str = "48 8B C4 48 89 58 08 57 48 81 EC A0 00 00 00 33";
    pub const SoundSystem__SomeUtlSymbolFunc: &str = "48 89 74 24 18 57 48 83 EC 20 48 63 F2 48 8B F9";
    pub const SoundSystem_ptr: &str = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 89 15";
}

pub mod tier0 {
    pub const CVar_ptr: &str = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC E9";
    pub const Tier0__LoadKeyValues: &str = "48 89 5C 24 10 48 89 6C 24 18 48 89 7C 24 20 41 54 41 56 41 57 48 83 EC 40 45 33 E4";
    pub const Tier0__UtlBuffer: &str = "48 89 5C 24 08 57 48 83 EC 20 8B 41 04 8D 7A 08";
}

pub mod vphysics2 {
    pub const VPhysics2_Startup: &str = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 54 41 56 41 57 48 83 EC 70 48 83";
}

