//! C++ SDK header emitter — turns the raw schema dump into ready-to-use
//! classes with `SCHEMA_FIELD` accessors.
//!
//! # What this produces
//!
//! For each schema module (e.g. `client.dll`) we emit a single header
//! `sdk/<module>.hpp` whose contents look like this:
//!
//! ```cpp
//! // Generated by cs2-sdk - https://cs2-sdk.com
//! //
//! // build_number: 14152
//! // generated_at: 2026-04-21T22:16:38+01:00
//! //
//! // Drop this header into your internal cheat and call schema fields with:
//! //
//! //     auto* pawn = some_pawn_pointer;
//! //     int  hp    = pawn->m_iHealth();
//! //     pawn->m_iHealth() = 100;
//! //
//! // The macros below produce inline accessors that compute
//! //     reinterpret_cast<T&>(*((std::byte*)this + offset))
//! // so they are zero-overhead in release builds.
//!
//! #pragma once
//! #include "cs2sdk_macros.hpp"
//!
//! namespace sdk::client {
//!     class C_BasePlayerPawn;
//!
//!     class C_CSPlayerPawn : public C_BasePlayerPawn {
//!     public:
//!         SCHEMA_FIELD(int32_t,  m_iHealth,        0x344)
//!         SCHEMA_FIELD(QAngle,   m_angEyeAngles,   0x1334)
//!     };
//! }
//! ```
//!
//! # Why this is in a separate emitter
//!
//! The existing `output::schemas` emitter produces `constexpr offset =
//! 0xABC;` constants, which is what the original cs2-dumper consumers
//! expect. This emitter is *additive* — it leaves the original output
//! untouched and adds a parallel `sdk/` tree of header files that are
//! more ergonomic for cheat developers.
//!
//! # Type translation
//!
//! Schema type names (`"int32"`, `"CHandle< C_BaseEntity >"`,
//! `"CUtlVector< Vector >"`, ...) are mapped to their canonical C++
//! equivalents through [`map_schema_type`]. Anything we don't recognise
//! is forwarded as-is wrapped in a `using` so the file still compiles.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::analysis::{Class, Enum, SchemaMap};

use super::ident::{slugify, type_ident};

/// Render every schema module into its own `*.hpp` SDK file.
///
/// Returns a list of `(file_name, file_contents)` pairs. The file name is
/// the module slug (e.g. `client_dll.hpp`) and the contents are the full
/// header text including the build banner.
pub fn render_module_headers(
    schemas: &SchemaMap,
    buttons: &BTreeMap<String, u64>,
    build_number: Option<u32>,
    timestamp: &str,
) -> Vec<(String, String)> {
    let mut out = Vec::with_capacity(schemas.len());
    let mut module_data: Vec<(String, String, Vec<Class>, Vec<Enum>)> = Vec::with_capacity(schemas.len());
    let mut type_namespace_map: BTreeMap<String, String> = BTreeMap::new();
    // Cross-module dedup: a schema class registered in two modules
    // (common for shared bases like CBaseEntity in both client.dll and
    // server.dll) is only emitted in the FIRST module that contained it.
    // Without this we get conflicting types across `sdk::client::` and
    // `sdk::server::` for what is logically the same class.
    let mut seen_classes: BTreeSet<String> = BTreeSet::new();
    let mut seen_enums: BTreeSet<String> = BTreeSet::new();
    for (module, (classes, enums)) in schemas {
        let filtered_classes: Vec<Class> = classes
            .iter()
            .filter(|c| seen_classes.insert(sanitize_class_name(&c.name)))
            .cloned()
            .collect();
        let filtered_enums: Vec<Enum> = enums
            .iter()
            .filter(|e| seen_enums.insert(type_ident(&e.name)))
            .cloned()
            .collect();
        let ns = slugify(module.trim_end_matches(".dll"));
        for c in &filtered_classes {
            type_namespace_map
                .entry(sanitize_class_name(&c.name))
                .or_insert_with(|| ns.clone());
        }
        for e in &filtered_enums {
            let enum_name = type_ident(&e.name);
            type_namespace_map
                .entry(enum_name)
                .or_insert_with(|| ns.clone());
            type_namespace_map
                .entry(sanitize_class_name(&e.name))
                .or_insert_with(|| ns.clone());
        }

        let file_name = format!("{}.hpp", slugify(module));
        module_data.push((file_name, module.clone(), filtered_classes, filtered_enums));
    }

    for (file_name, module, filtered_classes, filtered_enums) in module_data {
        let body = render_one_module(
            &module,
            &filtered_classes,
            &filtered_enums,
            buttons,
            build_number,
            timestamp,
            &type_namespace_map,
        );
        out.push((file_name, body));
    }
    out
}

/// Topologically sort classes so that base classes are defined before derived classes.
/// Classes with no parent or whose parent is not in the list come first.
/// This prevents "base class undefined" errors during compilation.
fn topological_sort_classes(classes: &[Class]) -> Vec<&Class> {
    use std::collections::{HashMap, VecDeque};

    // Build a map of class name -> class reference
    let class_map: HashMap<String, &Class> = classes
        .iter()
        .map(|c| (sanitize_class_name(&c.name), c))
        .collect();

    // Build dependency graph: class -> set of classes that depend on it (children)
    let mut children: HashMap<String, Vec<String>> = HashMap::new();
    let mut parent_count: HashMap<String, usize> = HashMap::new();

    for c in classes {
        let sanitized_name = sanitize_class_name(&c.name);
        parent_count.entry(sanitized_name.clone()).or_insert(0);

        if let Some(parent) = &c.parent_name {
            let sanitized_parent = sanitize_class_name(parent);

            // Only count as a dependency if the parent exists in this module
            if class_map.contains_key(&sanitized_parent) {
                children
                    .entry(sanitized_parent.clone())
                    .or_insert_with(Vec::new)
                    .push(sanitized_name.clone());
                *parent_count.entry(sanitized_name).or_insert(0) += 1;
            }
        }
    }

    // Kahn's algorithm for topological sort
    let mut queue: VecDeque<String> = parent_count
        .iter()
        .filter(|(_, count)| **count == 0)
        .map(|(name, _)| name.clone())
        .collect();

    let mut sorted = Vec::with_capacity(classes.len());

    while let Some(class_name) = queue.pop_front() {
        if let Some(&class_ref) = class_map.get(&class_name) {
            sorted.push(class_ref);
        }

        // Decrease parent count for all children
        if let Some(child_list) = children.get(&class_name) {
            for child in child_list {
                if let Some(count) = parent_count.get_mut(child) {
                    *count -= 1;
                    if *count == 0 {
                        queue.push_back(child.clone());
                    }
                }
            }
        }
    }

    // If there are cycles or classes we missed, append them at the end
    if sorted.len() < classes.len() {
        for c in classes {
            let sanitized_name = sanitize_class_name(&c.name);
            if !sorted.iter().any(|&sc| sanitize_class_name(&sc.name) == sanitized_name) {
                sorted.push(c);
            }
        }
    }

    sorted
}

/// Render a tiny shared header (`cs2sdk_macros.hpp`) that defines the
/// `SCHEMA_FIELD` macro family the generated headers depend on.
///
/// We emit this once instead of repeating the macros at the top of every
/// header.
pub fn render_macros_header() -> String {
    r#"// Generated by cs2-sdk — https://cs2-sdk.com
//
// Shared macro definitions used by every generated SDK header.
// Include this file (directly or transitively) before any sdk/<module>.hpp.

#pragma once

// Prevent Windows.h min/max macros from interfering with field names
#ifndef NOMINMAX
#define NOMINMAX
#endif

// Undefine min/max macros if they were defined before this header
#ifdef min
#undef min
#endif
#ifdef max
#undef max
#endif

#include <cstddef>
#include <cstdint>
#include <utility>

// ============================================================================
// Source 2 Engine Type Aliases
// ============================================================================
// These types are used throughout the Source 2 schema but aren't defined
// in the engine headers. We provide minimal type aliases here so the SDK
// compiles standalone.

// Basic type aliases that Source 2 uses instead of stdint types
using int8 = std::int8_t;
using int16 = std::int16_t;
using int32 = std::int32_t;
using int64 = std::int64_t;
using uint8 = std::uint8_t;
using uint16 = std::uint16_t;
using uint32 = std::uint32_t;
using uint64 = std::uint64_t;
using float32 = float;
using float64 = double;

// Time-related types
using GameTime_t = float;
using GameTick_t = std::int32_t;

// Symbol/ID types - these are typically just integers or small structs
using PulseSymbol_t = std::uint64_t;
using PulseDocNodeID_t = std::uint32_t;
using PulseRuntimeChunkIndex_t = std::int32_t;
using PulseRegisterMap_t = std::uint64_t;
using WorldGroupId_t = std::uint32_t;
using ChangeAccessorFieldPathIndex_t = std::int32_t;

// Handle types - typically 32-bit indices
template <typename T>
using CHandle = std::uint32_t;

template <typename T>
using CStrongHandle = std::uint64_t;

// Container types - forward declarations with minimal implementation
template <typename T, typename A = void*>
class CUtlVector {
public:
    T* m_pElements;
    int m_Size;
    int m_Capacity;
};

template <typename T>
class CUtlLeanVector {
public:
    T* m_pElements;
    int m_Size;
};

template <typename T, int N>
class CUtlVectorFixedGrowable {
public:
    T m_Elements[N];
    int m_Size;
};

template <typename K, typename V, typename L = void*>
class CUtlOrderedMap {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

template <typename K, typename V = K, typename H = void*, typename E = void*>
class CUtlHashtable {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

// Animation network variable wrapper
template <typename T>
class CAnimNetVar {
public:
    T m_Value;
};

// Animation value wrapper
template <typename T>
class CAnimValue {
public:
    T m_Value;
};

// Network variable embedded vector - used for networked arrays
template <typename T, typename A = void*>
class CUtlVectorEmbeddedNetworkVar {
public:
    T* m_pElements;
    int m_Size;
    int m_Capacity;
};

// Alias for single-parameter version
template <typename T>
using C_UtlVectorEmbeddedNetworkVar = CUtlVectorEmbeddedNetworkVar<T>;

// Network variable base vector - used for networked arrays
template <typename T, typename A = void*>
class CNetworkUtlVectorBase {
public:
    T* m_pElements;
    int m_Size;
};

// Alias for single-parameter version
template <typename T>
using C_NetworkUtlVectorBase = CNetworkUtlVectorBase<T>;

// Network variable chainer - used for network variable change tracking
class CNetworkVarChainer {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

// String types - forward declarations
class CUtlString {
public:
    const char* m_pString;
};

class CUtlSymbolLarge {
public:
    std::uint64_t m_Id;
};

class CUtlBinaryBlock {
public:
    void* m_pData;
    int m_Size;
};

class CBufferString {
public:
    char m_buffer[256]; // Placeholder size
};

// Generic template wrappers referenced by schema
template <typename T>
class CVariantBase {
};

template <typename T>
class CAnimScriptParam {
};

template <typename T>
class CResourcePointer {
};

template <typename T>
class CResourceArray {
};

// Additional core types commonly referenced by schema
class Attribute_t {
public:
    std::uint8_t m_Data[16];
};

class CUtlSymbol {
public:
    std::uint32_t m_Id;
};

class CUtlStringTokenWithStorage {
public:
    std::uint64_t m_Id;
};

class CResourceString {
public:
    const char* m_pString;
};

class KeyValues {
public:
    void* m_pData;
};

class CEntityNameString {
public:
    const char* m_pString;
};

class CEntityKeyValues {
public:
    void* m_pData;
};

class IPhysicsJoint {
public:
    void* m_pData;
};

// Cross-module types referenced by client headers
class CBaseAnimGraphDestructibleParts_GraphController {
public:
    std::uint8_t m_Data[8];
};

class CEntityAttributeTable {
public:
    std::uint8_t m_Data[8];
};

class CNetworkTransmitComponent {
public:
    std::uint8_t m_Data[8];
};

class thinkfunc_t {
public:
    std::uint8_t m_Data[8];
};

class CNetworkVelocityVector {
public:
    std::uint8_t m_Data[8];
};

class CParticleProperty {
public:
    std::uint8_t m_Data[8];
};

enum class TakeDamageFlags_t : std::uint64_t {};
enum class EntityPlatformTypes_t : std::uint8_t {};
enum class MoveCollide_t : std::uint8_t {};
enum class MoveType_t : std::uint8_t {};
enum class BloodType : std::int32_t {};

struct PulseCursorID_t {
    std::uint32_t m_Id;
};

struct ParticleParamID_t {
    std::uint32_t m_Id;
};

enum class PhysInterfaceId_t : std::uint32_t {};

enum class CCSPlayerAnimationState_MoveType_t : std::uint8_t {};
enum class CCSPlayerAnimationState_GroundMoveState_t : std::uint8_t {};
enum class CCSPlayerAnimationState_Direction_t : std::uint8_t {};
enum class CCSPlayerAnimationState_AirAction_t : std::uint8_t {};

struct fltx4 {
    std::uint32_t v[4];
};

struct RotationVector {
    float x, y, z;
};

struct RadianEuler {
    float x, y, z;
};

struct DegreeEuler {
    float x, y, z;
};

// Smart pointer types
template <typename T>
class CSmartPtr {
public:
    T* m_pData;
};

// Relative array type
template <typename T>
class CRelativeArray {
public:
    std::int32_t m_nOffset;
    std::int32_t m_nCount;
};

// Lean vector with fixed growable size
template <typename T, int N>
class CUtlLeanVectorFixedGrowable {
public:
    T m_Elements[N];
    int m_Size;
    int m_Capacity;
};

// Math types - forward declarations
struct Vector {
    float x, y, z;
};

struct Vector2D {
    float x, y;
};

struct Vector4D {
    float x, y, z, w;
};

struct QAngle {
    float x, y, z;
};

struct Quaternion {
    float x, y, z, w;
};

struct matrix3x4_t {
    float m[3][4];
};

struct matrix3x4a_t {
    float m[3][4];
};

struct Color {
    std::uint8_t r, g, b, a;
};

struct AABB_t {
    Vector m_vMinBounds;
    Vector m_vMaxBounds;
};

// Rendering types
struct CRenderBufferBinding {
    std::uint64_t m_hBuffer;
    std::uint32_t m_nBindOffsetBytes;
};

// Additional Source 2 types
class CGlobalSymbol {
public:
    std::uint64_t m_Id;
};

class CColorGradient {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPiecewiseCurve {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class KeyValues3 {
public:
    void* m_pData;
};

// Material/Rendering descriptor types
struct CMaterialDrawDescriptor {
    std::uint8_t m_Data[128]; // Placeholder
};

struct CMeshletDescriptor {
    std::uint8_t m_Data[64]; // Placeholder
};

struct RTProxyDrawDescriptor_t {
    std::uint8_t m_Data[64]; // Placeholder
};

// Resource handle types - these are typically used for loading game resources
class InfoForResourceTypeIPulseGraphDef {};
class InfoForResourceTypeCModel {};
class InfoForResourceTypeCRenderMesh {};
class InfoForResourceTypeCCompositeMaterialKit {};
class InfoForResourceTypeCCompositeMaterial {};
class InfoForResourceTypeCNmSkeleton {};
class InfoForResourceTypeIMaterial2 {};
class InfoForResourceTypeIParticleSystemDefinition {};
class InfoForResourceTypeIParticleSnapshot {};
class InfoForResourceTypeCNmGraphDefinition {};
class InfoForResourceTypeCNmClip {};
class InfoForResourceTypeCEntityLump {};
class InfoForResourceTypeCChoreoSceneResource {};
class InfoForResourceTypeCPostProcessingResource {};

// Strong handle void type
using CStrongHandleVoid = std::uint64_t;

// Strong handle copyable template - used for resource handles that can be copied
template <typename T>
class CStrongHandleCopyable {
public:
    std::uint64_t m_hHandle;
};

// Weak handle template - used for weak references to resources
template <typename T>
class CWeakHandle {
public:
    std::uint64_t m_hHandle;
};

// Resource name typed template - used for typed resource names
template <typename T>
class CResourceNameTyped {
public:
    std::uint64_t m_nHashCode;
};

// Additional type aliases for animation system
using QuaternionStorage = Quaternion;
using VectorWS = Vector;
using VectorAligned = Vector;

// Additional forward declarations for Source 2 types
class CAnimParamHandle {
public:
    std::uint16_t m_Index;
};

class CAnimInputDamping {
public:
    float m_flSpeedFunction;
    float m_flSpeedScale;
};

class CTransform {
public:
    Vector m_vPosition;
    Quaternion m_orientation;
};

class CNmTarget {
public:
    std::uint8_t m_Data[48]; // Placeholder
};

class CParticleNamedValueRef {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulseValueFullType {
public:
    std::uint8_t m_Data[24]; // Placeholder
};

class CPulse_Variable {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CPulse_PublicOutput {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CPulse_Constant {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CPulse_DomainValue {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CPulse_Chunk {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulseCell_Base {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulse_InvokeBinding {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulse_CallInfo {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulse_BlackboardReference {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulse_OutputConnection {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CPulse_OutflowConnection {
public:
    std::uint8_t m_Data[72]; // Placeholder
};

class CPulse_ResumePoint {
public:
    std::uint8_t m_Data[72]; // Placeholder
};

class CPulseRuntimeMethodArg {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

// Additional type aliases
using PulseRuntimeCellIndex_t = std::int32_t;
using PulseRuntimeBlackboardReferenceIndex_t = std::int16_t;
using PulseRuntimeOutputIndex_t = std::int32_t;
using PulseRuntimeVarIndex_t = std::int32_t;
using MeshDrawPrimitiveFlags_t = std::uint32_t;
using VertexAlbedoFormat_t = std::uint8_t;
using AnimParamID = std::uint32_t;
using AnimNodeID = std::uint32_t;
using ParticleModelType_t = std::uint32_t;
using PulseMethodCallMode_t = std::uint32_t;
using NmIKBlendMode_t = std::uint32_t;
using AnimValueSource = std::uint32_t;
using OrientationWarpMode_t = std::uint32_t;
using OrientationWarpTargetOffsetMode_t = std::uint32_t;
using OrientationWarpRootMotionSource_t = std::uint32_t;
using fieldtype_t = std::uint32_t;
using ParticleAttributeIndex_t = std::int32_t;
using ParticleIndex_t = std::int32_t;

// Cross-module types that are referenced across different DLLs
class SceneEventId_t {
public:
    std::uint32_t m_nSceneEventId;
};

class SndOpEventGuid_t {
public:
    std::uint64_t m_nGuid;
};

class CNetworkViewOffsetVector {
public:
    Vector m_vecOffset;
};

enum class HitGroup_t : std::int32_t {
    HITGROUP_INVALID = -1,
    HITGROUP_GENERIC = 0x0,
    HITGROUP_HEAD = 0x1,
    HITGROUP_CHEST = 0x2,
    HITGROUP_STOMACH = 0x3,
    HITGROUP_LEFTARM = 0x4,
    HITGROUP_RIGHTARM = 0x5,
    HITGROUP_LEFTLEG = 0x6,
    HITGROUP_RIGHTLEG = 0x7,
    HITGROUP_NECK = 0x8,
    HITGROUP_UNUSED = 0x9,
    HITGROUP_GEAR = 0xA,
    HITGROUP_SPECIAL = 0xB,
    HITGROUP_COUNT = 0xC,
};

enum class RenderMode_t : std::uint8_t {
    kRenderNormal = 0x0,
    kRenderTransAlpha = 0x1,
    kRenderNone = 0x2,
    kRenderModeCount = 0x3,
};

enum class RenderFx_t : std::uint8_t {
    kRenderFxNone = 0x0,
    kRenderFxPulseSlow = 0x1,
    kRenderFxPulseFast = 0x2,
    kRenderFxPulseSlowWide = 0x3,
    kRenderFxPulseFastWide = 0x4,
    kRenderFxFadeSlow = 0x5,
    kRenderFxFadeFast = 0x6,
    kRenderFxSolidSlow = 0x7,
    kRenderFxSolidFast = 0x8,
    kRenderFxStrobeSlow = 0x9,
    kRenderFxStrobeFast = 0xA,
    kRenderFxStrobeFaster = 0xB,
    kRenderFxFlickerSlow = 0xC,
    kRenderFxFlickerFast = 0xD,
    kRenderFxFadeOut = 0xE,
    kRenderFxFadeIn = 0xF,
    kRenderFxPulseFastWider = 0x10,
    kRenderFxMax = 0x11,
};

enum class DecalRtEncoding_t : std::uint8_t {
    DECAL_RT_ENCODING_NONE = 0x0,
    DECAL_RT_ENCODING_NORMAL = 0x1,
    DECAL_RT_ENCODING_EMISSIVE = 0x2,
};

// Additional cross-module enum types
enum class PointOrientGoalDirectionType_t : std::uint32_t {};
enum class PointOrientConstraint_t : std::uint32_t {};
enum class ValueRemapperInputType_t : std::uint32_t {};
enum class ValueRemapperOutputType_t : std::uint32_t {};
enum class ValueRemapperHapticsType_t : std::uint32_t {};
enum class ValueRemapperMomentumType_t : std::uint32_t {};
enum class ValueRemapperRatchetType_t : std::uint32_t {};
enum class PlayerConnectedState : std::uint32_t {};
enum class EntityDisolveType_t : std::uint32_t {};
enum class GrenadeType_t : std::uint32_t {};
enum class BeamType_t : std::uint32_t {};
enum class BeamClipStyle_t : std::uint32_t {};

// CBitVec template
template <int N>
class CBitVec {
public:
    std::uint32_t m_Data[(N + 31) / 32];
};

// Additional missing types
class CSoundPatch;
enum class C_BaseCombatCharacter_WaterWakeMode_t : std::uint32_t {};
enum class DamageTypes_t : std::uint32_t {};
enum class WeaponGameplayAnimState : std::uint32_t {};
enum class CSWeaponMode : std::uint32_t {};
enum class DoorState_t : std::uint32_t {};
enum class CSPlayerBlockingUseAction_t : std::uint32_t {};
class CParticleCollectionFloatInput;
class CPerParticleFloatInput;
class CParticleCollectionVecInput;
enum class ParticleColorBlendType_t : std::uint32_t {};
class CPerParticleVecInput;
class CParticleRemapFloatInput;
enum class ParticleSetMethod_t : std::uint32_t {};
class CParticleCollectionRendererFloatInput;
class CParticleCollectionRendererVecInput;
enum class ParticleNamedValueSource_t : std::uint32_t {};
enum class ParticleDirectionNoiseType_t : std::uint32_t {};
enum class AnimationType_t : std::uint32_t {};
enum class IChoreoServices_ScriptState_t : std::uint32_t {};
enum class IChoreoServices_ChoreoState_t : std::uint32_t {};
class CGenericShapeProxy;
template <int N> class CTypedBitVec;
using BASEPTR = void*;
using ENTITYFUNCPTR = void*;
using USEPTR = void*;
enum class ScriptedMoveTo_t : std::uint32_t {};
enum class SharedMovementGait_t : std::uint32_t {};
enum class ScriptedHeldWeaponBehavior_t : std::uint32_t {};
enum class ESceneViewDebugOverlaysListenerDataType_t : std::uint32_t {};
enum class soundlevel_t : std::uint32_t {};
class CVariantDefaultAllocator;
enum class CFuncMover_Move_t : std::uint32_t {};
enum class CFuncMover_OrientationUpdate_t : std::uint32_t {};
enum class CFuncMover_TransitionToPathNodeAction_t : std::uint32_t {};
enum class CFuncMover_FollowEntityDirection_t : std::uint32_t {};
enum class CFuncMover_FollowConstraint_t : std::uint32_t {};
enum class CFuncRotator_Rotate_t : std::uint32_t {};
class IPhysicsBody;
enum class CLogicBranchList_LogicBranchListenerLastState_t : std::uint32_t {};
enum class INavObstacle_NavObstacleType_t : std::uint32_t {};
class constraint_hingeparams_t;
enum class JointMotion_t : std::uint32_t {};
enum class DynamicContinuousContactBehavior_t : std::uint32_t {};
enum class CPhysicsProp_CrateType_t : std::uint32_t {};
class InfoForResourceTypeCVoiceContainerBase;
class InfoForResourceTypeCVMixListResource;
template<typename T> class CSteamAudioMovableBakedData;
class IPLCompressedEnergyFields;
class IPLProbeBatch;
class IPLScene;
class IPLStaticMesh;
class FourVectors;
class FourQuaternions;
template<typename T> class SphereBase_t;
class CUtlVectorSIMDPaddedVector;
enum class ParticleColorBlendMode_t : std::uint32_t {};
class CParticleTransformInput;
class CParticleVariableRef;
class CParticleModelInput;

// Forward declarations for classes and types
class CAnimGraphControllerManager;
class CAnimGraphControllerBase;
class IPhysicsRagdollControl;
class SceneRequestHandle_t;
class SceneOpportunityHandle_t;
class CCSPlayerAnimationState;
using HSCRIPT = void*;

enum class PointTemplateClientOnlyEntityBehavior_t : std::uint32_t {};
enum class PointTemplateOwnerSpawnGroupType_t : std::uint32_t {};
enum class QuestProgress_Reason : std::uint32_t {};
enum class PointWorldTextJustifyHorizontal_t : std::uint32_t {};
enum class PointWorldTextJustifyVertical_t : std::uint32_t {};
enum class PointWorldTextReorientMode_t : std::uint32_t {};

// Animation and transform types
class CMotionTransform {
public:
    Vector m_vPosition;
    Quaternion m_qOrientation;
    float m_flScale;
};

class RenderInputLayoutField_t {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CAnimVariant {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CGlobalSymbolCaseSensitive {
public:
    std::uint64_t m_Id;
};

// Resource info types for texture and animation data
class InfoForResourceTypeCTextureBase {
public:
    std::uint8_t m_Data[8]; // Placeholder - resource handle
};

class InfoForResourceTypeCAnimData {
public:
    std::uint8_t m_Data[8]; // Placeholder - resource handle
};

// Physics types
class RnSphereDesc_t {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class RnCapsuleDesc_t {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class RnHullDesc_t {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class RnMeshDesc_t {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class RnSoftbodyParticle_t {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class RnSoftbodySpring_t {
public:
    std::uint8_t m_Data[16]; // Placeholder
};

class RnSoftbodyCapsule_t {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

// Additional forward declarations for nested types
class CNmVectorInfoNode_Info_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CNmFloatAngleMathNode_Operation_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CNmFloatMathNode_Operator_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CNmTargetInfoNode_Info_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CSplitScreenSlot {
public:
    std::uint8_t m_Data[8]; // Placeholder
};

class CUtlStringToken {
public:
    std::uint32_t m_nHashCode;
};

class CResourceName {
public:
    std::uint64_t m_nHashCode;
};

class CNmTimeConditionNode_ComparisonType_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CNmTimeConditionNode_Operator_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CNmSyncEventIndexConditionNode_TriggerMode_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CModelAnimNameWithDeltas {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

class CNmParticleEvent_Type_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CNmStateNode_TimedEvent_t_Comparison_t {
public:
    std::uint8_t m_Data[4]; // Placeholder
};

class CKV3MemberNameWithStorage {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

class CRotation {
public:
    std::uint8_t m_Data[4]; // Placeholder - likely a quaternion or rotation representation
};

class InfoForResourceTypeCPhysAggregateData {
public:
    std::uint8_t m_Data[8]; // Placeholder - resource handle
};

class InfoForResourceTypeCAnimationGroup {
public:
    std::uint8_t m_Data[8]; // Placeholder - resource handle
};

class InfoForResourceTypeCSequenceGroupData {
public:
    std::uint8_t m_Data[8]; // Placeholder - resource handle
};

class CRangeFloat {
public:
    float m_flMin;
    float m_flMax;
};

class Range_t {
public:
    float m_flMin;
    float m_flMax;
};

struct PackedAABB_t {
    std::uint32_t m_nPackedMin;
    std::uint32_t m_nPackedMax;
};

// Entity index type - used for entity identification
struct CEntityIndex {
    std::int32_t m_Value;
};

// Physics types - forward declarations
struct PhysFeModelDesc_t {
    std::uint8_t m_Data[128]; // Placeholder
};

// Rendering types
enum class RenderPrimitiveType_t : std::uint32_t {
    RENDER_PRIM_TRIANGLES = 0,
    RENDER_PRIM_POINTS = 1,
    RENDER_PRIM_LINES = 2,
    RENDER_PRIM_TRIANGLE_STRIP = 3,
};

// KeyValues3 member name set
class CKV3MemberNameSet {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

// Particle system interface
class IParticleCollection {
public:
    virtual ~IParticleCollection() = default;
    std::uint8_t m_Data[128]; // Placeholder
};

// Compression template class - used for data compression in animation system
template <typename T>
class CCompressor {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

// Nested enum/class types that appear in schema - these are typically enums or small structs
// They are referenced with :: in the schema but sanitized to _ in the generated code
using CNmSoundEvent_Position_t = std::uint8_t;
using CNmRootMotionData_SamplingMode_t = std::uint8_t;
using CNmFloatComparisonNode_Comparison_t = std::uint8_t;
using CNmIDComparisonNode_Comparison_t = std::uint8_t;
using CNmTargetWarpNode_TargetUpdateRule_t = std::uint8_t;
using CNmFloatAngleMathNode_Operator_t = std::uint8_t;
using CNmFloatMathNode_Operation_t = std::uint8_t;
using CNmTimeConditionNode_Comparison_t = std::uint8_t;
using CNmSyncEventIndexConditionNode_Comparison_t = std::uint8_t;
using CNmStateNode_Comparison_t = std::uint8_t;
using CNmCurrentSyncEventNode_Mode_t = std::uint8_t;
using CNmCurrentSyncEventNode_InfoType_t = std::uint8_t;
using CNmVectorInfoNode_Component_t = std::uint8_t;
using CNmTargetInfoNode_Info_e = std::uint32_t;
using CNmParticleEvent_Mode_t = std::uint32_t;
using CNmTransitionNode_Flags_t = std::uint8_t;
using CNmEventTargetEntity_t = std::uint32_t;
using CNmRootMotionOverrideNode_Flags_t = std::uint8_t;
using MedalRank_t = std::uint32_t;

// Base component classes - these are base classes for player/controller components
class CPlayerPawnComponent {
public:
    std::uint8_t m_Data[8]; // Placeholder
};

class CPlayerControllerComponent {
public:
    std::uint8_t m_Data[8]; // Placeholder
};

// Entity IO output type - used for entity input/output system
class CEntityIOOutput {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

// Entity output template - used for typed entity outputs
template <typename T>
class CEntityOutputTemplate {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

// Point camera settings - used for camera configuration
struct PointCameraSettings_t {
    std::uint8_t m_Data[64]; // Placeholder
};

// Light effect type - used for light effects
struct C4LightEffect_t {
    std::uint8_t m_Data[32]; // Placeholder
};

// Player state type - used for player state tracking
struct CSPlayerState {
    std::uint8_t m_Data[32]; // Placeholder
};

// Performance mode type - used for performance settings
using PerformanceMode_t = std::uint32_t;

// Breakable contents type - used for breakable props
using BreakableContentsType_t = std::uint32_t;

// Particle attachment type - used for particle system attachments
using ParticleAttachment_t = std::uint32_t;

// Precipitation filter type - used for weather effects
using PrecipitationFilter_t = std::uint32_t;

// Observer interpolation state - used for spectator camera
using ObserverInterpState_t = std::uint32_t;

// Sequence handle type - used for animation sequences
using HSequence = std::uint32_t;

// Animation loop mode type - used for animation playback
using AnimLoopMode_t = std::uint32_t;

// Button state type - used for input button tracking
class CInButtonState {
public:
    std::uint64_t m_pnButtons[3];
};

// Animation algorithm type - used for animation system
using AnimationAlgorithm_t = std::uint32_t;

// External animation graph handle - used for animation graphs
using ExternalAnimGraphHandle_t = std::uint32_t;

// Networked quantized float - used for network compression
class CNetworkedQuantizedFloat {
public:
    float m_flValue;
};

// Sequence finish notify state - used for animation sequence notifications
using SequenceFinishNotifyState_t = std::uint32_t;

// Resource ID type - used for resource identification
using ResourceId_t = std::uint64_t;

// Skeleton animation controller - base class for animation controllers
class CSkeletonAnimationController {
public:
    std::uint8_t m_Data[128]; // Placeholder
};

// Animation graph instance - used for animation graph instances
class CNmGraphInstance {
public:
    std::uint8_t m_Data[256]; // Placeholder
};

// External animation graph struct - used for external animation graphs
struct ExternalAnimGraph_t {
    std::uint8_t m_Data[64]; // Placeholder
};

// Physics motion controller interface - used for physics simulation
class IPhysicsMotionController {
public:
    virtual ~IPhysicsMotionController() = default;
    std::uint8_t m_Data[64]; // Placeholder
};

// Filter type - used for entity filtering
struct filter_t {
    std::uint8_t m_Data[32]; // Placeholder
};

// Soundevent path corner pair - used for sound events
struct SoundeventPathCornerPairNetworked_t {
    std::uint8_t m_Data[32]; // Placeholder
};

// Model config handle - used for model configuration
using ModelConfigHandle_t = std::uint32_t;

// Solid type - used for collision detection
using SolidType_t = std::uint8_t;

// Surrounding bounds type - used for bounding box calculations
using SurroundingBoundsType_t = std::uint8_t;

// Shard solid type - used for breakable glass/props
enum class ShardSolid_t : std::uint8_t {
    SHARD_SOLID = 0x0,
    SHARD_DEBRIS = 0x1,
};

// Fix angle set type - used for view angle changes
enum class FixAngleSet_t : std::uint8_t {
    None = 0x0,
    Absolute = 0x1,
    Relative = 0x2,
};

// Animation graph parameter optional reference template - used for animation graph parameters
template <typename T>
class CAnimGraph2ParamOptionalRef {
public:
    std::uint8_t m_Data[24]; // Placeholder
};

// Animation graph parameter auto-reset optional reference - used for animation graph parameters
class CAnimGraph2ParamAutoResetOptionalRef {
public:
    std::uint8_t m_Data[24]; // Placeholder
};

// Additional enum types used in weapon and entity systems
using attributeprovidertypes_t = std::uint32_t;
using ENPCBehaviorOverride_t = std::uint32_t;
using InteractionPriority_t = std::uint32_t;
using CSWeaponType = std::uint32_t;
using CSWeaponCategory = std::uint32_t;
using gear_slot_t = std::uint32_t;
using loadout_slot_t = std::uint32_t;
using CSWeaponSilencerType = std::uint32_t;

// Firing mode float - used for weapon firing modes
class CFiringModeFloat {
public:
    float m_flValues[2];
};

// Firing mode int - used for weapon firing modes
class CFiringModeInt {
public:
    std::int32_t m_nValues[2];
};

// Skill float - used for difficulty scaling
class CSkillFloat {
public:
    float m_flValue;
};

// Transform world space - used for entity transforms
class CTransformWS {
public:
    Vector m_vPosition;
    Quaternion m_qOrientation;
};

// Network origin cell coord quantized vector - used for networked positions
class CNetworkOriginCellCoordQuantizedVector {
public:
    std::uint16_t m_cellX;
    std::uint16_t m_cellY;
    std::uint16_t m_cellZ;
    std::uint16_t m_nOutsideWorld;
    Vector m_vecX;
    Vector m_vecY;
    Vector m_vecZ;
};

// Entity handle - used for entity references
class CEntityHandle {
public:
    std::uint32_t m_Index;
};

// Player slot - used for player identification
class CPlayerSlot {
public:
    std::int32_t m_Value;
};

// Physics aggregate instance interface - used for physics
class IPhysAggregateInstance {
public:
    virtual ~IPhysAggregateInstance() = default;
    std::uint8_t m_Data[64]; // Placeholder
};

// Observer mode - used for spectator camera modes
enum class ObserverMode_t : std::uint32_t {
    OBS_MODE_NONE = 0,
    OBS_MODE_FIXED = 1,
    OBS_MODE_IN_EYE = 2,
    OBS_MODE_CHASE = 3,
    OBS_MODE_ROAMING = 4,
};

// Sound event name - used for sound system
class CSoundEventName {
public:
    std::uint8_t m_Data[32]; // Placeholder
};

// Attachment handle - used for model attachments
using AttachmentHandle_t = std::uint16_t;

// Timeline compression - used for animation timeline compression
enum class TimelineCompression_t : std::uint32_t {
    TIMELINE_COMPRESSION_SUM = 0,
    TIMELINE_COMPRESSION_COUNT_PER_INTERVAL = 1,
    TIMELINE_COMPRESSION_AVERAGE = 2,
    TIMELINE_COMPRESSION_AVERAGE_BLEND = 3,
    TIMELINE_COMPRESSION_TOTAL = 4,
};

// Kill types - used for kill tracking
enum class EKillTypes_t : std::uint32_t {
    KILL_NONE = 0,
    KILL_DEFAULT = 1,
    KILL_HEADSHOT = 2,
    KILL_BLAST = 3,
    KILL_BURN = 4,
    KILL_SLASH = 5,
};

// Weapon sound - used for weapon sound events
enum class WeaponSound_t : std::uint32_t {
    WEAPON_SOUND_EMPTY = 0,
    WEAPON_SOUND_SINGLE_SHOT = 1,
    WEAPON_SOUND_SINGLE_SHOT_NPC = 2,
    WEAPON_SOUND_DOUBLE_SHOT = 3,
    WEAPON_SOUND_DOUBLE_SHOT_NPC = 4,
    WEAPON_SOUND_BURST = 5,
    WEAPON_SOUND_RELOAD = 6,
    WEAPON_SOUND_RELOAD_NPC = 7,
    WEAPON_SOUND_MELEE_MISS = 8,
    WEAPON_SOUND_MELEE_HIT = 9,
    WEAPON_SOUND_MELEE_HIT_WORLD = 10,
    WEAPON_SOUND_SPECIAL1 = 11,
    WEAPON_SOUND_SPECIAL2 = 12,
    WEAPON_SOUND_SPECIAL3 = 13,
    WEAPON_SOUND_TAUNT = 14,
    WEAPON_SOUND_DEPLOY = 15,
};

// Attachment name symbol with storage - used for model attachments
class CAttachmentNameSymbolWithStorage {
public:
    std::uint8_t m_Data[64]; // Placeholder
};

// Item flag types - used for item flags
enum class ItemFlagTypes_t : std::uint32_t {
    ITEM_FLAG_NONE = 0,
    ITEM_FLAG_CAN_SELECT_WITH_USE = 1,
    ITEM_FLAG_NOAUTORELOAD = 2,
    ITEM_FLAG_NOAUTOSWITCHEMPTY = 4,
    ITEM_FLAG_LIMITINWORLD = 8,
    ITEM_FLAG_EXHAUSTIBLE = 16,
    ITEM_FLAG_DOHITLOCATIONDMG = 32,
    ITEM_FLAG_NOAMMOPICKUPS = 64,
    ITEM_FLAG_NOITEMPICKUP = 128,
};

// Ammo index - used for ammunition types
using AmmoIndex_t = std::int32_t;

// Rumble effect - used for controller rumble
enum class RumbleEffect_t : std::uint32_t {
    RUMBLE_INVALID = 0xFFFFFFFF,
    RUMBLE_STOP_ALL = 0,
    RUMBLE_PISTOL = 1,
    RUMBLE_357 = 2,
    RUMBLE_SMG1 = 3,
    RUMBLE_AR2 = 4,
    RUMBLE_SHOTGUN_SINGLE = 5,
    RUMBLE_SHOTGUN_DOUBLE = 6,
    RUMBLE_AR2_ALT_FIRE = 7,
    RUMBLE_RPG_MISSILE = 8,
    RUMBLE_CROWBAR_SWING = 9,
    RUMBLE_AIRBOAT_GUN = 10,
    RUMBLE_JEEP_ENGINE_LOOP = 11,
    RUMBLE_FLAT_LEFT = 12,
    RUMBLE_FLAT_RIGHT = 13,
    RUMBLE_FLAT_BOTH = 14,
    RUMBLE_DMG_LOW = 15,
    RUMBLE_DMG_MED = 16,
    RUMBLE_DMG_HIGH = 17,
    RUMBLE_FALL_LONG = 18,
    RUMBLE_FALL_SHORT = 19,
    RUMBLE_PHYSCANNON_OPEN = 20,
    RUMBLE_PHYSCANNON_PUNT = 21,
    RUMBLE_PHYSCANNON_LOW = 22,
    RUMBLE_PHYSCANNON_MEDIUM = 23,
    RUMBLE_PHYSCANNON_HIGH = 24,
};

// ============================================================================
// SDK Helper Functions and Macros
// ============================================================================

namespace sdk {

    // Helper to determine the const-qualified return type
    // For non-pointer types: const T&
    // For pointer types: T* const& (const pointer, not pointer-to-const)
    template <typename T>
    struct const_field_type {
        using type = const T&;
    };

    template <typename T>
    struct const_field_type<T*> {
        using type = T* const&;
    };

    // Convert `this + offset` to a typed reference. Zero-overhead in
    // release builds; produces an lvalue you can read or assign to.
    template <typename T>
    inline T& field_ref(void* base, std::ptrdiff_t off) noexcept {
        return *reinterpret_cast<T*>(reinterpret_cast<std::byte*>(base) + off);
    }

    template <typename T>
    inline typename const_field_type<T>::type field_ref(const void* base, std::ptrdiff_t off) noexcept {
        return *reinterpret_cast<T*>(const_cast<std::byte*>(reinterpret_cast<const std::byte*>(base)) + off);
    }

} // namespace sdk

// SCHEMA_FIELD(type, name, offset)
//
// Expands to a pair of inline accessors:
//
//     T&       name()       { return sdk::field_ref<T>(this, off); }
//     const T& name() const { return sdk::field_ref<T>(this, off); }
//
// For pointer types, the const version returns T* const& (const pointer, not pointer to const)
// Use it as: `pawn->m_iHealth() = 100;`
#define SCHEMA_FIELD(TYPE, NAME, OFFSET)                                           \
    inline TYPE&       NAME()       noexcept { return ::sdk::field_ref<TYPE>(this, (OFFSET)); } \
    inline auto        NAME() const noexcept -> decltype(::sdk::field_ref<TYPE>(this, (OFFSET))) { return ::sdk::field_ref<TYPE>(this, (OFFSET)); }

// SCHEMA_PAD(name, size) — anonymous padding when you want to
// pre-declare a struct layout exactly. Optional.
#define SCHEMA_PAD(NAME, SIZE) std::byte NAME[(SIZE)]
"#
    .to_string()
}

fn render_one_module(
    module: &str,
    classes: &[Class],
    enums: &[Enum],
    buttons: &BTreeMap<String, u64>,
    build_number: Option<u32>,
    timestamp: &str,
    type_namespace_map: &BTreeMap<String, String>,
) -> String {
    let ns = slugify(module.trim_end_matches(".dll"));
    let mut s = String::with_capacity(64 * 1024);

    write_banner(&mut s, module, classes.len(), enums.len(), build_number, timestamp);
    s.push_str("#pragma once\n");
    s.push_str("#include \"cs2sdk_macros.hpp\"\n\n");

    writeln!(s, "namespace sdk::{} {{", ns).ok();
    writeln!(s).ok();

    // CS2_BUILD constant removed from per-module files — the running
    // build number lives in `manifest.json` and `cs2sdk.hpp` only.
    let _ = build_number;

    // Add buttons enum for client.dll
    if module == "client.dll" && !buttons.is_empty() {
        writeln!(s, "    enum class InputButton : std::uint64_t {{").ok();
        for (name, value) in buttons {
            writeln!(s, "        {} = 0x{:X},", name, value).ok();
        }
        writeln!(s, "    }};\n").ok();
    }

    // Build a set of class names to detect collisions with enum names
    let class_names: BTreeSet<String> = classes.iter().map(|c| sanitize_class_name(&c.name)).collect();

    // Forward-declare every class up front so order-of-definition / cyclic
    // references are not a problem.
    let mut declared: BTreeSet<String> = BTreeSet::new();
    for c in classes {
        let sanitized_name = sanitize_class_name(&c.name);
        if declared.insert(sanitized_name.clone()) {
            writeln!(s, "    class {};", sanitized_name).ok();
        }
    }
    writeln!(s).ok();

    // Track emitted enum names to prevent duplicates
    let mut emitted_enums: BTreeSet<String> = BTreeSet::new();

    // Enums first so classes can reference them.
    for e in enums {
        // Determine if enum has negative values
        let has_negative = e.members.iter().any(|m| (m.value as i64) < 0);

        let underlying = match e.alignment {
            1 => if has_negative { "std::int8_t" } else { "std::uint8_t" },
            2 => if has_negative { "std::int16_t" } else { "std::uint16_t" },
            4 => if has_negative { "std::int32_t" } else { "std::uint32_t" },
            8 => if has_negative { "std::int64_t" } else { "std::uint64_t" },
            _ => continue,
        };

        // Check for name collision with classes and append _e suffix if needed
        let enum_name = type_ident(&e.name);
        let mut final_enum_name = if class_names.contains(&enum_name) {
            format!("{}_e", enum_name)
        } else {
            enum_name.clone()
        };

        // Handle duplicate enum names by appending a counter
        let mut counter = 2;
        while emitted_enums.contains(&final_enum_name) {
            final_enum_name = if class_names.contains(&enum_name) {
                format!("{}_e{}", enum_name, counter)
            } else {
                format!("{}_{}", enum_name, counter)
            };
            counter += 1;
        }

        // Mark this enum name as emitted
        emitted_enums.insert(final_enum_name.clone());

        writeln!(s, "    enum class {} : {} {{", final_enum_name, underlying).ok();
        for m in &e.members {
            // Cast to signed for proper display of negative values
            let value = m.value as i64;
            if value < 0 {
                writeln!(s, "        {} = {},", sanitize_enum_member(&m.name), value).ok();
            } else {
                writeln!(s, "        {} = {:#X},", sanitize_enum_member(&m.name), m.value as u64).ok();
            }
        }
        writeln!(s, "    }};\n").ok();
    }

    // Classes: emit with parent inheritance + SCHEMA_FIELD accessors.
    // Sort classes topologically so base classes are defined before derived classes.
    let sorted_classes = topological_sort_classes(classes);

    for c in &sorted_classes {
        write_class_doc(&mut s, c);
        let sanitized_name = sanitize_class_name(&c.name);
        let parent = c
            .parent_name
            .as_deref()
            .map(sanitize_class_name)
            .map(|p| format!(" : public {}", p))
            .unwrap_or_default();
        writeln!(s, "    class {}{} {{", sanitized_name, parent).ok();
        writeln!(s, "    public:").ok();

        // First pass: emit type aliases for fields with commas in their types
        let mut alias_counter = 0;
        let mut field_aliases: Vec<(usize, String)> = Vec::new();
        for (idx, f) in c.fields.iter().enumerate() {
            let cpp_ty = map_schema_type(&f.type_name, &ns, type_namespace_map);
            if cpp_ty.contains(',') {
                let alias_name = format!("_Type{}", alias_counter);
                writeln!(s, "        using {} = {};", alias_name, cpp_ty).ok();
                field_aliases.push((idx, alias_name));
                alias_counter += 1;
            }
        }

        // Second pass: emit SCHEMA_FIELD with type aliases where needed
        for (idx, f) in c.fields.iter().enumerate() {
            let cpp_ty = map_schema_type(&f.type_name, &ns, type_namespace_map);

            // Skip bitfield types - they can't be accessed via SCHEMA_FIELD macro
            if f.type_name.starts_with("bitfield:") {
                writeln!(
                    s,
                    "        // SKIPPED: {} (bitfield type not supported)",
                    f.name,
                )
                .ok();
                continue;
            }

            let safe_ty = field_aliases.iter()
                .find(|(i, _)| *i == idx)
                .map(|(_, alias)| alias.clone())
                .unwrap_or(cpp_ty.clone());
            writeln!(
                s,
                "        SCHEMA_FIELD({:<32}, {:<48}, {:#X}) // {}",
                safe_ty, f.name, f.offset, f.type_name,
            )
            .ok();
        }
        writeln!(s, "    }};\n").ok();
    }

    // Add manual CEconItem class for server.dll (not in schema)
    if ns == "server" {
        writeln!(s, "    // CEconItem").ok();
        writeln!(s, "    //   Manual addition - server-side inventory item").ok();
        writeln!(s, "    //   fields: 11").ok();
        writeln!(s, "    class CEconItem {{").ok();
        writeln!(s, "    public:").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint64_t                   , m_ulID                                          , 0x10) // uint64").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint64_t                   , m_ulOriginalID                                  , 0x18) // uint64").ok();
        writeln!(s, "        SCHEMA_FIELD(void*                           , m_pCustomData                                   , 0x20) // void*").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint32_t                   , m_unAccountID                                   , 0x28) // uint32").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint32_t                   , m_unInventory                                   , 0x2C) // uint32").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint16_t                   , m_unDefIndex                                    , 0x30) // uint16").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint16_t                   , m_nQuality                                      , 0x32) // uint16").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint16_t                   , m_nRarity                                       , 0x32) // uint16").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint16_t                   , m_iItemSet                                      , 0x34) // uint16").ok();
        writeln!(s, "        SCHEMA_FIELD(bool                            , m_bSOUpdateFrame                                , 0x38) // bool").ok();
        writeln!(s, "        SCHEMA_FIELD(std::uint32_t                   , m_unFlags                                       , 0x3C) // uint32").ok();
        writeln!(s, "    }};\n").ok();
    }

    writeln!(s, "}} // namespace sdk::{}", ns).ok();
    s
}

fn write_banner(
    s: &mut String,
    module: &str,
    classes: usize,
    enums: usize,
    build_number: Option<u32>,
    timestamp: &str,
) {
    let _ = build_number;  // intentionally unused — see manifest.json
    writeln!(s, "// Generated by cs2-sdk — https://cs2-sdk.com").ok();
    writeln!(s, "//").ok();
    writeln!(s, "// module:        {}", module).ok();
    writeln!(s, "// classes:       {}", classes).ok();
    writeln!(s, "// enums:         {}", enums).ok();
    writeln!(s, "// generated_at:  {}", timestamp).ok();
    writeln!(s, "//").ok();
    writeln!(s, "// Use:").ok();
    writeln!(s, "//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);").ok();
    writeln!(s, "//   pawn->m_iHealth() = 100;").ok();
    writeln!(s).ok();
}

fn write_class_doc(s: &mut String, c: &Class) {
    writeln!(s, "    // {}", c.name).ok();
    if let Some(parent) = &c.parent_name {
        writeln!(s, "    //   parent: {}", parent).ok();
    }
    writeln!(s, "    //   fields: {}", c.fields.len()).ok();
}

/// Map a Source 2 schema type string to its canonical C++ equivalent.
///
/// We intentionally err on the side of "leave as-is" — anything we don't
/// understand is wrapped in a forward-decl-friendly pointer or returned
/// verbatim. This keeps the header useful even for types we haven't yet
/// hand-mapped.
fn map_schema_type(
    raw: &str,
    current_ns: &str,
    type_namespace_map: &BTreeMap<String, String>,
) -> String {
    let t = raw.trim();

    // Handle array types: Type[N] -> Type (the SCHEMA_FIELD macro handles array access)
    if let Some(bracket_pos) = t.find('[') {
        let base_type = &t[..bracket_pos];
        return map_schema_type(base_type, current_ns, type_namespace_map);
    }

    let mapped = match t {
        "bool" => "bool".into(),
        "char" => "char".into(),
        "int8"  | "int8_t"   => "std::int8_t".into(),
        "uint8" | "uint8_t"  => "std::uint8_t".into(),
        "int16" | "int16_t"  => "std::int16_t".into(),
        "uint16"| "uint16_t" => "std::uint16_t".into(),
        "int32" | "int32_t"  => "std::int32_t".into(),
        "uint32"| "uint32_t" => "std::uint32_t".into(),
        "int64" | "int64_t"  => "std::int64_t".into(),
        "uint64"| "uint64_t" => "std::uint64_t".into(),
        "float32" | "float"  => "float".into(),
        "float64" | "double" => "double".into(),
        "Vector"             => "::Vector".into(),
        "Vector2D"           => "::Vector2D".into(),
        "Vector4D"           => "::Vector4D".into(),
        "QAngle"             => "::QAngle".into(),
        "Quaternion"         => "::Quaternion".into(),
        "Color"              => "::Color".into(),
        "CUtlString"         => "::CUtlString".into(),
        "CUtlSymbolLarge"    => "::CUtlSymbolLarge".into(),
        "CUtlBinaryBlock"    => "::CUtlBinaryBlock".into(),
        "matrix3x4_t"        => "::matrix3x4_t".into(),
        "AABB_t"             => "::AABB_t".into(),
        "CRenderBufferBinding" => "::CRenderBufferBinding".into(),
        // Time types
        "GameTime_t"         => "::GameTime_t".into(),
        "GameTick_t"         => "::GameTick_t".into(),
        // Symbol/ID types
        "PulseSymbol_t"      => "::PulseSymbol_t".into(),
        "PulseDocNodeID_t"   => "::PulseDocNodeID_t".into(),
        "PulseRuntimeChunkIndex_t" => "::PulseRuntimeChunkIndex_t".into(),
        "PulseRegisterMap_t" => "::PulseRegisterMap_t".into(),
        "WorldGroupId_t"     => "::WorldGroupId_t".into(),
        "ChangeAccessorFieldPathIndex_t" => "::ChangeAccessorFieldPathIndex_t".into(),
        _ => {
            // Templated containers are extremely common in the schema:
            // CHandle< C_X >, CUtlVector< T >, CNetworkedQuantizedFloat, ...
            // Need to sanitize nested class names in template parameters but preserve std::
            // e.g., CUtlVector<CPulseCell_Timeline::TimelineEvent_t> -> CUtlVector<CPulseCell_Timeline_TimelineEvent_t>
            // but std::pair<A,B> stays as std::pair<A,B>

            // Simple approach: replace all :: with _ EXCEPT when preceded by "std"
            let mut result = String::new();
            let chars: Vec<char> = t.chars().collect();
            let mut i = 0;

            while i < chars.len() {
                if i + 1 < chars.len() && chars[i] == ':' && chars[i + 1] == ':' {
                    // Found ::, check if it's std::
                    let is_std = i >= 3 &&
                                 chars[i-3] == 's' &&
                                 chars[i-2] == 't' &&
                                 chars[i-1] == 'd';

                    if is_std {
                        // Keep std::
                        result.push_str("::");
                    } else {
                        // Replace :: with _
                        result.push('_');
                    }
                    i += 2; // Skip both colons
                } else {
                    result.push(chars[i]);
                    i += 1;
                }
            }

            result
        }
    };

    qualify_cross_module_type_refs(&mapped, current_ns, type_namespace_map)
}

fn qualify_cross_module_type_refs(
    cpp_type: &str,
    current_ns: &str,
    type_namespace_map: &BTreeMap<String, String>,
) -> String {
    let chars: Vec<char> = cpp_type.chars().collect();
    let mut out = String::with_capacity(cpp_type.len());
    let mut i = 0;

    while i < chars.len() {
        if chars[i].is_ascii_alphabetic() || chars[i] == '_' {
            let start = i;
            i += 1;
            while i < chars.len() && (chars[i].is_ascii_alphanumeric() || chars[i] == '_') {
                i += 1;
            }

            let token: String = chars[start..i].iter().collect();
            let scoped = start >= 2 && chars[start - 2] == ':' && chars[start - 1] == ':';
            if !scoped {
                if let Some(owner_ns) = type_namespace_map.get(&token) {
                    if owner_ns != current_ns {
                        out.push_str("::sdk::");
                        out.push_str(owner_ns);
                        out.push_str("::");
                        out.push_str(&token);
                        continue;
                    }
                }
            }

            out.push_str(&token);
            continue;
        }

        out.push(chars[i]);
        i += 1;
    }

    out
}

fn sanitize_enum_member(raw: &str) -> String {
    let mut s = String::with_capacity(raw.len());
    for c in raw.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            s.push(c);
        } else {
            s.push('_');
        }
    }
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        s.insert(0, '_');
    }
    s
}

/// Sanitize class names by replacing `::` with `_` to avoid nested class syntax issues.
/// For example, `CPulseCell_Timeline::TimelineEvent_t` becomes `CPulseCell_Timeline_TimelineEvent_t`.
fn sanitize_class_name(raw: &str) -> String {
    raw.replace("::", "_")
}

/// Optional helper: collect every (class, parent) pair so a TUI / docs
/// page can render the class hierarchy. Currently unused by the emitter
/// itself; exposed for future tooling.
pub fn class_hierarchy(schemas: &SchemaMap) -> BTreeMap<String, Option<String>> {
    let mut out = BTreeMap::new();
    for (_, (classes, _)) in schemas {
        for c in classes {
            out.insert(c.name.clone(), c.parent_name.clone());
        }
    }
    out
}
