// Auto-generated by cs2-universal-dumper. Do not edit.
// Each constant is an IDA-style byte pattern; scan it at
// runtime with your favourite pattern scanner.

namespace CS2Sdk.Signatures;

public static class Signatures
{
    public static class animationsystem
    {
        public const string Animation__ShouldUpdateSequences = "48 89 5C 24 08 48 89 74 24 18 57 48 83 EC 20 49";
        public const string AnimationSystemUtils_ptr = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 83 EC 28 48 8B CA 48 8D 15";
    }
    public static class client
    {
        public const string AddNametagEntity = "40 55 53 56 48 8D AC 24 B0 FC FF FF 48 81 EC 50";
        public const string AddStattrakEntity = "48 8B C4 48 89 58 08 48 89 70 10 57 48 83 EC 50 33 F6 8B FA";
        public const string AnimGraphRebuild = "40 55 56 48 83 EC 28 4C 89 74 24 58 48 8B F1 80";
        public const string ApplyEconCustomization = "48 89 5C 24 08 57 48 83 EC 20 8B FA 48 8B D9 E8 ? ? ? ? 48 8B CB E8 ? ? ? ? 48 85 C0 74";
        public const string AutowallInit = "40 53 48 83 EC 20 48 8B D9 48 81 C1 D8 0D 00 00";
        public const string AutowallTraceData = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 50 48 8B 09 49";
        public const string AutowallTracePos = "40 55 56 41 54 41 55 41 57 48 8B EC 48 83 EC 60";
        public const string BulkRegenIterator = "57 48 83 EC 40 0F B6 F9 E8 ? ? ? ? 48 85 C0";
        public const string CAM_ThinkReturn = "BA 04 00 00 00 FF 15 E6 A1 5E 01 84 C0 0F 84 C2";
        public const string CAttributeStringFill = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 20 33 F6 0F 57 C0 0F";
        public const string CAttributeStringInit = "48 8B C2 48 83 C8 02 45 84 C0 48 0F 44 C2 48 89 41 08 48 8D 05 1F B4 3A";
        public const string CBaseEntity_ChangeModel = "40 53 48 83 EC 20 48 8B D9 4C 8B C2 48 8B 0D ED";
        public const string CBaseEntity_TakeDamageOld = "40 55 53 56 57 41 54 48 8D 6C 24 E0 48 81 EC 20";
        public const string CBaseModelEntity_SetBodygroup = "85 D2 0F 88 ? ? ? ? 55 53 56 41 56 48 8B EC";
        public const string CBodyComponent = "48 83 EC 38 48 8B 05 ? ? ? ? 48 85 C0 0F 85 ? ? ? ? 48 89 5C 24 40 B9 50 00 00 00 48 89 6C 24 48 4C 89 64 24 30 4C 89 74 24 28 4C 89 7C";
        public const string CBodyComponentSkeletonInstance = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 8B 0D 36 15";
        public const string CBufferStringInit = "48 89 5C 24 10 57 48 83 EC 30 8B 41 04 48 8D 79";
        public const string CCSGOInput__CreateMove = "48 8B C4 4C 89 40 18 48 89 48 08 55 53 41 54 41";
        public const string CCSGameRules = "4C 8D 05 ? ? ? ? 48 8D 15 ? ? ? ? 48 8D 0D 6B B2 21";
        public const string CCSGameRulesProxy = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 5B E5 0F";
        public const string CCSPlayerController = "40 55 41 56 41 57 48 8B EC 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 1E 03 00";
        public const string CCSPlayerController = "40 55 41 56 41 57 48 8B EC 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 1E 03 00";
        public const string CCSPlayerController_ActionTrackingServices = "40 55 41 56 41 57 48 8B EC 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 1E 03 00";
        public const string CCSPlayerController_DamageServices = "40 55 41 56 41 57 48 8B EC 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 1E 03 00";
        public const string CCSPlayerController_InGameMoneyServices = "40 55 41 56 41 57 48 8B EC 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 1E 03 00";
        public const string CCSPlayerController_InventoryServices = "40 55 41 56 41 57 48 8B EC 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 1E 03 00";
        public const string CCSPlayerInventory__GetItemInLoadout = "40 55 48 83 EC 30 49 63 E8 ? ? ? ? 87 94 01";
        public const string CCSPlayerPawn = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 1B 6C C3";
        public const string CCSPlayer_BulletServices = "40 53 48 83 EC 50 8B 15 ? ? ? ? 48 8B D9 65 48 8B 04 25 58 00 00 00 B9 98 00 00 00 48 8B 04 D0 8B 04 01 39 05 DE 98";
        public const string CCSPlayer_BulletServices = "40 53 48 83 EC 50 8B 15 ? ? ? ? 48 8B D9 65 48 8B 04 25 58 00 00 00 B9 98 00 00 00 48 8B 04 D0 8B 04 01 39 05 DE 98";
        public const string CCSPlayer_CameraServices = "48 89 5C 24 08 57 48 83 EC 30 E8 ? ? ? ? 8B 15 CB 48 D3";
        public const string CCSPlayer_HostageServices = "40 53 48 83 EC 50 8B 15 ? ? ? ? 48 8B D9 65 48 8B 04 25 58 00 00 00 B9 98 00 00 00 48 8B 04 D0 8B 04 01 39 05 DE 98";
        public const string CCSPlayer_ItemServices = "40 53 48 83 EC 50 8B 15 ? ? ? ? 48 8B D9 65 48 8B 04 25 58 00 00 00 B9 98 00 00 00 48 8B 04 D0 8B 04 01 39 05 AE 0D";
        public const string CCSPlayer_MovementServices = "48 83 EC 28 8B 0D ? ? ? ? 65 48 8B 04 25 58 00 00 00 BA 98 00 00 00 48 8B 04 C8 8B 04 02 39 05 63 44 AC 01 0F 8F 36";
        public const string CCSPlayer_MovementServices = "48 83 EC 28 8B 0D ? ? ? ? 65 48 8B 04 25 58 00 00 00 BA 98 00 00 00 48 8B 04 C8 8B 04 02 39 05 63 44 AC 01 0F 8F 36";
        public const string CCSPlayer_PingServices = "48 89 5C 24 18 55 48 8B EC 48 83 EC 60 8B 15 AD";
        public const string CCSPlayer_RunCommand_Context = "48 8B C4 48 81 EC C8 00 00 00 48 89 58 10 48 89";
        public const string CCSPlayer_UseServices = "48 89 5C 24 08 57 48 83 EC 30 E8 ? ? ? ? 8B 15 AB 23 CC";
        public const string CCSPlayer_WaterServices = "48 83 EC 28 8B 0D ? ? ? ? 65 48 8B 04 25 58 00 00 00 BA 98 00 00 00 48 8B 04 C8 8B 04 02 39 05 5B D4 A8 01 0F 8F 43";
        public const string CCSPlayer_WeaponServices = "48 83 EC 28 8B 0D ? ? ? ? 65 48 8B 04 25 58 00 00 00 BA 98 00 00 00 48 8B 04 C8 8B 04 02 39 05 53 E6 A8 01 0F 8F C4";
        public const string CCSPlayer_WeaponServices = "48 83 EC 28 8B 0D ? ? ? ? 65 48 8B 04 25 58 00 00 00 BA 98 00 00 00 48 8B 04 C8 8B 04 02 39 05 53 E6 A8 01 0F 8F C4";
        public const string CCSWeaponBase = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 8B 86 06";
        public const string CCSWeaponBaseGun = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 EB 85 06";
        public const string CCSWeaponBaseVData = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 8B 81 88";
        public const string CCollisionProperty = "48 83 EC 58 83 F9 01 0F 85 ? ? ? ? 48 89 5C 24 60 48 8D 05 47 1C 81";
        public const string CCompositeMaterialManager_AddPanoramaPanelRenderRequest_Caller = "41 2B C4 41 89 07 48 85 F6 74 7E 49 8B 5F 08 49";
        public const string CDecoyProjectile = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 7B 98 09";
        public const string CEconItemSchema__GetAttributeDefinitionByName = "48 89 5C 24 10 48 89 6C 24 18 57 41 56 41 57 48 83 EC 60 48";
        public const string CEconItemView__GetCustomPaintKitIndex = "48 89 5C 24 08 57 48 83 EC 40 8B 15 ? ? ? ? 48 8B F9 65 48 8B 04 25 58 00 00 00 B9 98 00 00 00 48 8B 04 D0 8B 04 01 39 05 22 1B 31 01 0F 8F";
        public const string CFlashbangProjectile = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 6B 76 80";
        public const string CFogController = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 8B 8A 56";
        public const string CGameSceneNode = "41 56 48 83 EC 30 4C 8B F2 85 C9 74 25 83 F9 06 74 09 33 C0 48 83 C4 30 41 5E C3 48 8B 02 49 8B CE 48 8D 54 24 58 FF 10 48 8B 00 48 83 C4 30 41";
        public const string CGameSceneNode_BuildBoneMergeWork = "40 55 56 57 41 54 41 55 41 56 41 57 48 83 EC 50 48 8D 6C 24 50 80 A1 06";
        public const string CGameSceneNode_PerformBatchedInvalidatePhysicsRecursive = "40 57 48 81 EC 90 00 00 00 84 C9 74 4D BF 01 00";
        public const string CGameSceneNode_StartHierarchicalAttachment = "48 89 5C 24 10 48 89 6C 24 18 48 89 74 24 20 57 41 54 41 55 41 56 41 57 48 83 EC 30 48 8B F9 8B";
        public const string CGameTrace_TraceShape_Client = "48 89 5C 24 20 48 89 4C 24 08 55 57 41 54 41 55";
        public const string CGlowProperty = "48 83 EC 58 83 F9 01 0F 85 ? ? ? ? 48 8D 05 ? ? ? ? C7 44 24 30 00 00 00 80 89 4C 24 28 4C 8D 05 ? ? ? ? 48 89 44 24 48 48 8D 4C 24";
        public const string CGlowProperty_OnGlowTypeChanged = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8B 05 32 F8";
        public const string CHEGrenadeProjectile = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 CB 75 80";
        public const string CInputPtrGlobal = "4C 8B 05 ? ? ? ? 41 8B 80 50 0B 00 00 85 C0";
        public const string CMolotovProjectile = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 9B 96 09";
        public const string CPaintKitDefinitions_FindOrCreateByName = "48 89 5C 24 08 48 89 6C 24 18 56 57 41 56 48 81 EC 50 01 00";
        public const string CPaintKitDefinitions_LoadDefaultKit = "48 89 6C 24 20 56 57 41 54 41 55 41 57 48 81 EC";
        public const string CPostProcessingVolume = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 FB 3C 54";
        public const string CS2ItemEditor_BuildTemplateMaterialFromFile = "48 89 54 24 10 55 53 41 55 41 57 48 8D AC 24 18";
        public const string CSBaseGunFireData_fn = "48 8B C4 55 53 56 57 41 54 41 55 41 56 41 57 48 8D 68 A8 48";
        public const string CSGOInput_ptr = "48 8B 0D ? ? ? ? 4C 8B C6 8B 10 E8";
        public const string CSGOInput_resolved = "48 8B 0D ? ? ? ? 8B 10 E8 ? ? ? ? 45 32 FF";
        public const string CSkeletonInstance = "40 57 48 83 EC 20 48 8B FA 85 C9 74 23 83 F9 06 74 08 33 C0 48 83 C4 20 5F C3 48 8B 02 48 8B CF 48 8D 54 24 48 FF 10 48 8B 00 48 83 C4 20 5F C3";
        public const string CSkeletonInstance__SetMeshGroupMask = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8D 99 50 01";
        public const string CSkeletonInstance_GetTransformsForHitboxList = "48 89 5C 24 18 55 56 57 41 55 41 57 48 81 EC A0";
        public const string CSkeletonInstance_OnBodyGroupChoiceChanged = "48 89 5C 24 08 57 48 83 EC 20 49 63 D8 49 8B F9";
        public const string CSkeletonInstance_PostDataUpdate = "48 8B C4 4C 89 40 18 89 50 10 55 57 48 8D A8 68";
        public const string CSkeletonInstance_SetMaterialGroup = "3B 91 C4 03 00 00 74 24 89 91 C4 03 00 00 48 8B";
        public const string CSkeletonInstance_SetMeshGroupMask = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 49 8B 00 49 8B";
        public const string CSmokeGrenadeProjectile = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 FB 95 09";
        public const string CTonemapController2 = "48 83 EC 28 48 8D 15 ? ? ? ? 48 8D 4C 24 38 E8 CB FD 58";
        public const string CUtlVector_CompositeMaterialInput_AddToTail = "41 B9 88 02 00 00 8B 57 14 81 E2 FF FF FF 3F 8D 71 01 44 8B";
        public const string C_AttributeContainer = "41 56 48 83 EC 40 4C 8B F2 83 F9 06 0F 87 C7 02";
        public const string C_BaseEntity = "48 89 5C 24 10 48 89 74 24 18 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
        public const string C_BaseModelEntity = "40 55 41 56 48 83 EC 78 4C 8B F2 83 F9 06 0F 87 ? ? ? ? 48 63 C1 48 8D 15 D2 7F";
        public const string C_BasePlayerPawn = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
        public const string C_C4 = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
        public const string C_CSPlayerPawn = "40 56 48 83 EC 40 48 8B F2 83 F9 06 0F 87 85 01";
        public const string C_CSPlayerPawnBase = "40 53 48 83 EC 20 65 48 8B 04 25 58 00 00 00 8B 0D 3B D4 96";
        public const string C_CSWeaponBase = "40 56 48 83 EC 40 48 8B F2 85 C9 74 27 83 F9 06 74 08 33 C0 48 83 C4 40 5E C3 48 8B 02 48 8B CE 48 8D 54 24 68 FF 90 70 01 00 00 48 8B 00 48 83";
        public const string C_EconEntity_BuildLegacyGloveSkinMaterial = "40 55 56 57 48 8D AC 24 30 FD FF FF 48 81 EC D0";
        public const string C_EconEntity_BuildLegacyWeaponSkinMaterial = "40 55 53 41 57 48 8D AC 24 00 FE FF FF 48 81 EC";
        public const string C_EconEntity_BuildModernWeaponSkinMaterial = "48 85 C9 0F 84 ? ? ? ? 48 8B C4 48 89 50 10";
        public const string C_EconEntity_BuildNametagOverlayMaterial = "40 55 53 56 48 8D AC 24 B0 FC FF FF 48 81 EC 50";
        public const string C_EconItemView = "40 56 48 83 EC 20 48 8B F2 85 C9 74 27 83 F9 06";
        public const string C_EconWearable_OnNewCustomMaterials = "48 89 5C 24 08 57 48 83 EC 20 8B DA 48 8B F9 E8 ? ? ? ? F6 C3 01 0F";
        public const string C_Hostage = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
        public const string C_Inferno = "48 89 5C 24 10 48 89 74 24 18 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
        public const string C_PlantedC4 = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
        public const string C_SmokeGrenadeProjectile = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 65 48 8B 04 25 58 00 00 00 48 8D 35 ? ? ? ? 8B 0D ? ? ? ? 33 FF BA 98 00 00 00 48 8B 1C C8";
        public const string CacheParticleEffect = "4C 8B DC 53 48 81 EC 90 00 00 00 F2 0F 10 05 65";
        public const string CalcSpread = "48 8B C4 48 89 58 08 48 89 68 18 48 89 70 20 57 41 54 41 55 41 56 41 57 48 81 EC E0";
        public const string CalcViewmodelTransform_v2 = "48 89 5C 24 20 55 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 80 48 81 EC 80 01 00 00 48 8B FA 48";
        public const string CalcViewmodelView = "40 53 48 83 EC 60 48 8B 41 08 49 8B D8 8B 48 30";
        public const string CalculateInterpolation = "48 83 EC 08 4C 8B 0D ? ? ? ? 4C 8B DA 48 8B";
        public const string ClearHUDWeaponIcon = "4C 8B DC 55 57 48 83 EC 48 48 63 41 68 48 8B F9";
        public const string ClientModeCSNormal_OnEvent = "40 53 57 48 81 EC 78 02 00 00 48 8B CA 48 8B FA";
        public const string ClientMode_ptr = "48 8D 0D ? ? ? ? 48 69 C0 ? ? ? ? 48 03 C1 C3 CC CC";
        public const string Client_DispatchSpawn = "4C 8B DC 55 56 48 83 EC 78 49 8B 68 08 48 8B F1";
        public const string CompositeMaterialPanoramaPanel_Init = "48 8B C4 4C 89 40 18 55 56 41 56 48 8D 68 A1 48";
        public const string ComputeRandomSeed = "48 89 5C 24 08 57 48 81 EC F0 00 00 00 F3 0F 10";
        public const string ConCommand_firstperson = "48 83 EC 28 48 8B 0D ? ? ? ? 48 8D 54 24 30 48 8B 01 FF 90 08 03 00 00 83 7C 24 30 00 75 69";
        public const string ConCommand_thirdperson = "48 83 EC 38 48 8B 0D ? ? ? ? 48 8D 54 24 40";
        public const string ConvarGet = "8B D0 48 8D 0D ? ? ? ? E8 ? ? ? ? 0F 10 45 D0 83 F0";
        public const string CreateBaseTypeCache = "40 53 48 83 EC 20 4C 8B 49 18 44 8B D2 4C 63 41";
        public const string CreateEntityByClassName = "4C 8D 05 ? ? ? ? 4C 8B CF BA 03 00 00 00 FF 15 55 0B 30";
        public const string CreateInterface = "4C 8B 0D ? ? ? ? 4C 8B D2 4C 8B D9 4D 85 C9";
        public const string CreateNewSubtickMoveStep = "48 89 5C 24 10 57 48 83 EC 20 33 DB 48 8B F9 48 85 C9 75 2D B9 38 00 00 00 E8 E2 DA";
        public const string CreateParticleEffect = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 50 F3 0F 10 1D 21";
        public const string CreateSOSubclassEconItem = "48 83 EC 28 B9 48 00 00 00 E8 ? ? ? ? 48 85";
        public const string DamageFeedbackEmitter = "48 89 4C 24 08 55 53 41 54 41 55 41 57 48 8D AC";
        public const string DestroyParticle = "83 FA FF 0F 84 ? ? ? ? 41 54 41 56 41 57 48";
        public const string DispatchEffect = "48 89 5C 24 08 57 48 83 EC 70 48 8B F9 48 8B DA";
        public const string DispatchSpawn_caller = "4C 8B DC 55 56 48 83 EC 78 49 8B 68 08 48 8B F1";
        public const string DrawLegs = "40 55 53 56 41 56 41 57 48 8D AC 24 A0 FB FF FF";
        public const string DrawOverHead = "40 53 48 83 EC 20 48 8B D9 83 FA FF 75 17 48 8B";
        public const string DrawSmokeVertex = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 83 EC 40 48 8B 9C 24 88 00 00 00 4D 8B F8 48 8B FA 48 8B";
        public const string EmitSoundByHandle = "40 53 48 83 EC 30 4C 89 4C 24 20 48 8B D9 45 8B";
        public const string FX_FireBullets = "48 8B C4 4C 89 48 20 48 89 50 10 55 53 57 41 54";
        public const string FX_FireBullets = "48 8B C4 4C 89 48 20 48 89 50 10 55 53 57 41 54";
        public const string FindHudElement = "48 8D 15 ? ? ? ? 45 33 C0 B9 01 00 00 00 FF 15 23 2C B4";
        public const string FindHudElement_panorama = "4C 8B DC 53 48 83 EC 50 48 8B 05 ? ? ? ? 48";
        public const string FindSOCache = "48 89 5C 24 08 57 48 83 EC 30 4C 8B 52 08 48 8B";
        public const string FirstPersonLegs = "40 55 53 56 41 56 41 57 48 8D AC 24 A0 FB FF FF";
        public const string FlashOverlay = "85 D2 0F 88 ? ? ? ? 48 89 4C 24 08 55 53 41";
        public const string ForceButtonsDown = "40 53 57 41 56 48 81 EC 30 02 00 00 48 83 79 38";
        public const string GameEntitySystemPtr = "48 8B 1D ? ? ? ? 48 89 1D ? ? ? ?";
        public const string GameEventManager_AddListener = "48 89 5C 24 10 48 89 6C 24 18 56 57 41 56 48 83 EC 50 41 0F";
        public const string GameEventManager_UnserializeEvent = "48 8B C4 48 89 50 10 55 41 54 41 55 41 56 48 8D";
        public const string GameRules_ptr = "48 8B 1D ? ? ? ? 48 8D 54 24 ? 0F 28 D0 48 8D 4C 24 ?";
        public const string GetBBox_ptr = "48 8B 0D ? ? ? ? 48 85 C9 74 ? ? ? ? 48 FF A0 ? ? ? ? 48 8D 05";
        public const string GetBaseEntity = "4C 8D 49 10 81 FA FE 7F 00 00 77 47 8B CA C1 F9";
        public const string GetBonePositionByName = "40 53 48 83 EC 20 48 8B 89 30 03 00 00 48 8B DA 48 8B 01 FF 50 50 48 8B";
        public const string GetChatObject = "48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 8B 05 ? ? ? ? 48";
        public const string GetClientSystem = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 30 48";
        public const string GetControllerCmd = "40 53 48 83 EC 20 8B DA E8 ? ? ? ? 4C 8B C0";
        public const string GetEconItemSystem = "48 83 EC 28 48 8B 05 ? ? ? ? 48 85 C0 0F 85 ? ? ? ? 48 89 5C 24 30 B9 50 00 00 00 48 89 74 24 40 4C 89 74 24 20 E8 ? ? ? ? 33 F6 48";
        public const string GetEntityByIndex = "4C 8D 49 10 81 FA FE 7F 00 00 77 47 8B CA C1 F9";
        public const string GetEntityHandle = "48 85 C9 74 32 48 8B 49 10 48 85 C9 74 29 44 8B";
        public const string GetGlowColor = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 48 8B F2 48 8B F9 48 8B";
        public const string GetHitGroup = "40 53 48 83 EC 20 48 83 79 10 00 48 8B D9 74 16";
        public const string GetInstanceS = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 8B 91 ? ? ? ? B8";
        public const string GetInt2_Event = "48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 20 48 63 FA 41 8B F0 4C 8B F1 45 85 C0 74 79 8B 41 10 48 89 5C 24 30 8B 19 41 03 D8 4C 89 7C 24 38";
        public const string GetInventoryManager = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 0F B6 81 6B";
        public const string GetLocalControllerById = "48 83 EC 28 83 F9 FF 75 17 48 8B 0D ? ? ? ? 48 8D 54 24 30 48 8B 01 FF 90 08 03 00 00 8B 08 48 63 C1 4C 8D 05 36 A5";
        public const string GetLocalPawn = "48 83 EC 28 83 F9 FF 75 17 48 8B 0D ? ? ? ? 48 8D 54 24 30 48 8B 01 FF 90 08 03 00 00 8B 08 48 63 C1 4C 8D 05 36 A5";
        public const string GetLocalPlayer_dispatcher = "48 83 EC 38 48 8B 05 ? ? ? ? 48 85 C0 0F 85 ? ? ? ? 48 89 5C 24 40 B9 50 00 00 00 48 89 74 24 50 4C 89 74 24 28 4C 89 7C 24 20 E8 4E 66";
        public const string GetMatrixForView = "40 53 48 83 EC 60 0F 29 74 24 50 0F 57 DB F3 0F";
        public const string GetPlayerByIndex_export = "48 83 EC 28 4C 8D 05 ? ? ? ? 48 8D 15 0E DF";
        public const string GetPlayerInterp = "40 53 48 83 EC 20 48 8B D9 48 8B 0D ? ? ? ? 48 83 C1 08";
        public const string GetRemovedAimPunch_E8 = "40 53 48 83 EC 20 48 8B 89 90 14 00 00 48 8B DA";
        public const string GetRemovedAimpunch = "F2 0F 10 44 24 60 F2 0F 11 84 24 88 00 00 00 FF 15 8C 30 7F";
        public const string GetSurfaceData = "48 63 41 10 48 8B 0D ? ? ? ? 48 C1 E0 05 48";
        public const string GetTickBase = "8B 81 B8 06 00 00 C3 CC CC CC CC CC CC CC CC CC";
        public const string GetTraceInfo = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 60 48 8B E9 0F";
        public const string GetUserCmdManager = "41 56 41 57 48 83 EC 48 48 8D 54 24 68 E8 CE A1";
        public const string GetViewAngles = "4C 8B C1 85 D2 74 08 48 8D 05 ? ? ? ? C3 8B";
        public const string GetWeaponInAccuracyRecoveryTime = "48 89 5C 24 08 57 48 83 EC 30 48 8B D9 E8 9E 52";
        public const string GetWorldFovResolver = "40 53 48 83 EC 50 48 8B D9 E8 ? ? ? ? 48 85";
        public const string GlobalLightUpdateState = "40 57 48 81 EC C0 00 00 00 48 8B F9 BA FF FF FF";
        public const string GlobalVariables_ptr = "48 89 15 ? ? ? ? 48 89 42";
        public const string GloveApply_PerTick = "40 55 56 57 48 8D AC 24 30 FD FF FF 48 81 EC D0";
        public const string GlowManager_ptr = "48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 8B 41";
        public const string GlowObjectManager_GetInstance = "48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 8B 41 38 C3";
        public const string HandleBulletPenetration = "48 8B C4 44 89 48 20 48 89 50 10 48 89 48 08 55 57 41 57 48";
        public const string HandleEntityList = "48 8B C4 4C 89 48 20 4C 89 40 18 48 89 50 10 55 56 41 57 48";
        public const string HandleTeamIntro = "48 83 EC 28 45 0F B6 08 44 38 89 04 0F 00 00 74";
        public const string HudChatPrintf = "4C 89 44 24 18 4C 89 4C 24 20 53 B8 40 10 00 00";
        public const string InfoForResourceTypeCCompositeMaterialKit_TypeManager = "40 55 41 56 48 83 EC 78 4C 8B F2 83 F9 06 0F 87 ? ? ? ? 48 63 C1 48 8D 15 32 6F";
        public const string InfoForResourceTypeCCompositeMaterial_TypeManager = "40 55 41 56 48 83 EC 68 48 8B EA 83 F9 06 0F 87 ? ? ? ? 48 63 C1 48 8D 15 E2 69";
        public const string InitFilter = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 0F B6 41 39 33 FF 24 C9 C7";
        public const string InitPlayerMovementTraceFilter = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 0F B6 41 39 33 FF C7 41 34";
        public const string InitTraceInfo = "40 55 41 55 41 57 48 83 EC 30 4C 8B 3D 6F CC EE";
        public const string IsGlowing = "0F B6 41 51 C3 CC CC CC CC CC CC CC CC CC CC CC";
        public const string KillFeedbackEmitter = "48 89 5C 24 08 48 89 74 24 18 48 89 7C 24 20 55 41 56 41 57 48 8B EC 48 81 EC 80 00";
        public const string LevelInit = "40 55 56 41 56 48 8D 6C 24 90 48 81 EC 70 01 00";
        public const string LoadFileForMe = "40 55 57 41 56 48 83 EC 20 4C 63 71 18 33 FF 48";
        public const string LoadPath = "48 89 74 24 20 57 48 83 EC 20 44 8B 49 04 BF FF FF FF 7F 44 23 CF 48 8B F1 41 8B C8 45 85 C0 74 30 83 E9 ? ? ? ? F9 01 0F 85 ? ? ? ? 41";
        public const string LocalPlayerController_ptr = "48 8B 05 ? ? ? ? 41 89 BE";
        public const string LookupBone = "40 53 48 83 EC 20 48 8B 89 30 03 00 00 48 8B DA 48 8B 01 FF 50 50 48 8B";
        public const string ModulationUpdate = "48 89 5C 24 08 57 48 83 EC 20 8B FA 48 8B D9 E8 ? ? ? ? 84 C0 0F 84";
        public const string NoClipOnChange = "48 89 5C 24 10 48 89 74 24 18 48 89 7C 24 20 55 48 8B EC 48 83 EC 30 48 8D 05 AA 1A";
        public const string NoSpread1 = "48 89 5C 24 08 57 48 81 EC F0 00 00 00 F3 0F 10";
        public const string ParticleCollection = "48 89 5C 24 08 57 48 83 EC 20 0F 28 05 AF 37 2E";
        public const string ParticleManager_ptr = "48 8B 0D ? ? ? ? 41 B8 ? ? ? ? F3 0F 11 74 24 ? 48 C7 44 24 ? ? ? ? ?";
        public const string PhysicsRunThink_Ctrl = "48 89 5C 24 20 57 48 81 EC D0 06 00 00 48 8B 01";
        public const string PhysicsRunThink_Pawn = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 8B 81 74 03 00";
        public const string PlayVSound_client = "48 89 5C 24 08 48 89 74 24 18 48 89 7C 24 20 55 48 8D 6C 24 A9 48 81 EC 90 00 00 00";
        public const string Prediction_ptr = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 40 53 56 41 54";
        public const string ProcessImpacts = "48 8B C4 53 56 41 55 48 81 EC E0 00 00 00 44 0F";
        public const string ProcessMovement = "E9 ? ? ? ? 56 57 41 54 41 55 41 56 41 57 48";
        public const string RegenerateWeaponSkin = "40 55 53 41 57 48 8D AC 24 00 FE FF FF 48 81 EC";
        public const string RegenerateWeaponSkin_v2 = "40 55 53 41 57 48 8D AC 24 00 FE FF FF 48 81 EC";
        public const string RegenerateWeaponSkins = "48 83 EC 48 E8 ? ? ? ? 48 85 C0 0F 84 7F 00";
        public const string RenderDecals = "44 88 4C 24 20 55 53 57 41 54 41 55 48 8D 6C 24";
        public const string ReportHit = "40 53 48 83 EC 20 48 8D 05 ? ? ? ? 48 8D 59 08 48 89 01 F6 03 01 74 08 48 8B CB E8 AF FB EA";
        public const string RunCommand = "48 8B C4 48 81 EC C8 00 00 00 48 89 58 10 48 89";
        public const string RunCommand_processor = "48 8B C4 48 81 EC C8 00 00 00 48 89 58 10 48 89";
        public const string Scope_callsite = "E9 ? ? ? ? 48 83 EC 68 48 8B FA 44 0F 29 40";
        public const string SendChatMessage = "4C 89 44 24 18 4C 89 4C 24 20 53 B8 40 10 00 00";
        public const string Sensitivity_ptr = "48 8D 0D ? ? ? ? 66 0F 6E CD";
        public const string SetAbsOrigin_Pawn = "48 89 5C 24 08 57 48 83 EC 60 48 8B 01 48 8B FA 48 8B D9 FF";
        public const string SetBodyGroup_inv = "85 D2 0F 88 ? ? ? ? 53 55 48 83 EC 38 48 63";
        public const string SetCollisionBounds = "48 83 EC 38 F2 0F 10 02 8B 42 08 48 8D 54 24 20";
        public const string SetDynamicAttributeValue = "48 89 6C 24 20 57 41 56 41 57 48 81 EC A0 00 00 00 48 8B FA C7 44 24 20 00 00 00 00 4D 8B F8 4C 8D 0D ? ? ? ? 48 8B E9 ? ? ? ? CD 12 01";
        public const string SetDynamicAttributeValue_raw = "48 89 6C 24 20 57 41 56 41 57 48 81 EC A0 00 00 00 48 8B FA C7 44 24 20 00 00 00 00 4D 8B F8 4C 8D 0D ? ? ? ? 48 8B E9 ? ? ? ? CD 12 01";
        public const string SetMeshGroupMask = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8D 99 50 01";
        public const string SetModel = "40 53 48 83 EC 20 48 8B D9 4C 8B C2 48 8B 0D ED";
        public const string SetPlayerReady = "40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ? ? 48 8B CB FF";
        public const string SetPlayerReady = "40 53 48 83 EC 20 48 8B DA 48 8D 15 ? ? ? ? 48 8B CB FF";
        public const string SetTraceData = "48 89 6C 24 18 48 89 7C 24 20 41 56 48 83 EC 20 48 63 29 4C 8B F2 48 8B F9 3B 69 10 0F 85 ? ? ? ? F7 41 14 00 00 00 40 0F 85 ? ? ? ? 8B";
        public const string SetTypeKV3 = "40 53 48 83 EC 30 4C 8B 11 41 B9 16 00 00 00 49";
        public const string SetViewAngle = "85 D2 75 3D 48 63 81 50 0B 00 00 F2 41 0F 10 00";
        public const string SetupCmd = "48 83 EC 28 E8 ? ? ? ? 8B 80 10 59 00 00 48";
        public const string SetupMove = "48 89 5C 24 18 48 89 6C 24 20 56 57 41 56 48 83 EC 20 48 8B EA 4C 8B F1";
        public const string SetupMovementMoves = "48 8B CE E8 ? ? ? ? 48 8B 5C 24 50 48 8B 6C 24 58 48 83";
        public const string ShowMessageBox = "44 88 4C 24 20 53 41 56 41 57 48 81 EC 60 02 00";
        public const string SomeTimingFromPawn = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 49 63 D8 48 8B";
        public const string Spawner_PerTickOrchestrator = "48 8B C4 55 53 48 8D A8 E8 ? ? ? ? 81 EC 08";
        public const string SpectatorInput = "48 89 5C 24 10 55 56 57 41 56 41 57 48 8B EC 48 83 EC 60 48";
        public const string SpreadSeedGen = "48 89 5C 24 08 57 48 81 EC F0 00 00 00 F3 0F 10";
        public const string TestSurfaces = "40 53 57 41 56 48 83 EC 50 8B 84 24 90 00 00 00";
        public const string ThirdPersonOffHandler = "48 83 EC 28 48 8B 0D ? ? ? ? 48 8D 54 24 30 48 8B 01 FF 90 08 03 00 00 83 7C 24 30 00 75 69";
        public const string ThirdPersonOnHandler = "48 83 EC 38 48 8B 0D ? ? ? ? 48 8D 54 24 40";
        public const string TraceCreate = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 83 EC 50 F2 0F 10 02";
        public const string TraceGetInfo = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 60 48 8B E9 0F";
        public const string TraceHandleBulletPen = "48 8B C4 44 89 48 20 48 89 50 10 48 89 48 08 55 57 41 57 48";
        public const string TraceInitData = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8D 79 08 33";
        public const string TraceInitFilter = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 0F B6 41 39 33 FF 24 C9 C7";
        public const string TraceInitInfo = "40 55 41 55 41 57 48 83 EC 30 4C 8B 3D 6F CC EE";
        public const string TracePlayerBBox = "48 89 5C 24 18 55 57 41 54 41 55 41 56 48 8D 6C";
        public const string TraceShape = "48 89 5C 24 20 48 89 4C 24 08 55 57 41 54 41 55";
        public const string TraceShape_Client = "48 89 5C 24 20 48 89 4C 24 08 55 57 41 54 41 55";
        public const string TraceToExit = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 83 EC 50 F2 0F 10 02";
        public const string UpdateGlobalVars = "48 8B 0D ? ? ? ? 4C 8D 05 ? ? ? ? 48 85 D2 48 8D 05";
        public const string UpdatePostProcessing = "48 85 D2 0F 84 ? ? ? ? 48 89 5C 24 08 57 48 83 EC 60 80";
        public const string UpdatePostProcessing = "48 85 D2 0F 84 ? ? ? ? 48 89 5C 24 08 57 48 83 EC 60 80";
        public const string UpdateSkybox = "48 89 5C 24 08 57 48 83 EC 30 48 8B F9 E8 8E F1";
        public const string UpdateSubClass = "48 8B 41 10 48 8B D9 8B 50 30 C1 EA 04 F6 C2 01";
        public const string UpdateTurningInAccuracy = "40 56 48 81 EC 80 00 00 00 48 8B F1 BA FF FF FF";
        public const string VPhys2World_ptr = "4C 8B 25 ? ? ? ? 24";
        public const string ViewModelHideZoomed = "48 89 5C 24 20 55 56 57 41 54 41 56 48 8B EC 48 83 EC 50 48 8D 05 86 01";
        public const string ViewRender_ptr = "48 89 05 ? ? ? ? 48 8B C8 48 85 C0";
        public const string WeaponC4_ptr = "48 8B 15 ? ? ? ? 48 8B 5C 24 ? FF C0 89 05 ? ? ? ? 48 8B C6 48 89 34 EA 80 BE";
        public const string WriteSubtickFromEntry = "48 89 5C 24 18 55 57 41 56 48 8D 6C 24 C9 48 81";
        public const string draw_smoke_array = "40 55 41 54 41 55 48 8D AC 24 20 F9 FF FF 48 81";
        public const string draw_view_punch_v2 = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 40 49 8B E9 49 8B F8";
        public const string entity_list_ptr = "48 8B 1D ? ? ? ? 48 8D 46";
        public const string frame_stage_notify = "4C 8B 0D ? ? ? ? 48 8D 15 ? ? ? ? 48 8B 8F 38 04 00";
        public const string get_fov = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 40 49 8B E9 49 8B F8";
        public const string get_map_name = "48 83 EC 28 48 8B 0D ? ? ? ? 48 8B 01 FF 90 00 02 00 00";
        public const string get_view_angles_v2 = "4D 85 C0 74 72 85 D2 74 18 48 8D 05 ? ? ? ?";
        public const string global_vars_v2 = "48 89 1D ? ? ? ? FF 15 ? ? ? ? 84 C0 74 ? 8B 0D ? ? ? ? 4C 8D 0D ? ? ? ? 4C 8D 05 ? ? ? ? BA ? ? ? ? FF 15 ? ? ? ? 48 8B 74 24 ? 48 8B C3";
        public const string is_demo_or_hltv = "48 83 EC 28 48 8B 0D ? ? ? ? 48 8B 01 FF 90 50 01 00 00 84 C0 75 0D";
        public const string level_init_v2 = "40 55 56 41 56 48 8D 6C 24 B9 48 81 EC E0 00 00 00 48 8B 0D";
        public const string level_shutdown = "48 83 EC 28 48 8B 0D ? ? ? ? 48 8D 15 66 C4";
        public const string local_controller = "48 8B 05 ? ? ? ? 41 89 BE";
        public const string mark_interp_latch_flags_dirty = "40 53 56 57 48 83 EC 40 80 3D A1 97 10 02 00 8B";
        public const string on_add_entity_v2 = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 8B 81 C0 20";
        public const string override_view_short = "40 57 48 83 EC 60 48 8B FA E8 ? ? ? ? BA FF";
        public const string paintkit_prefab = "48 89 5C 24 10 48 89 6C 24 18 48 89 74 24 20 57 48 83 EC 30 48 8B D9 48 81 C1 80 11";
        public const string paintkit_seed = "48 89 4C 24 08 53 56 57 41 54 41 55 41 56 41 57 48 83 EC 50 65 48 8B 04";
        public const string paintkit_wear = "48 89 4C 24 08 53 56 57 41 54 41 55 41 56 41 57 48 83 EC 50 65 48 8B 04";
        public const string planted_c4_ptr = "48 8B 15 ? ? ? ? 48 8B 5C 24 ? FF C0 89 05 ? ? ? ? 48 8B C6 ? ? ? ? 80 BE ? ? ? ? 00";
        public const string remove_legs = "40 55 53 56 41 56 41 57 48 8D AC 24 A0 FB FF FF";
        public const string statTrak_killEater = "48 89 4C 24 08 53 56 57 41 54 41 55 41 56 41 57 48 83 EC 50 65 48 8B 04";
        public const string statTrak_scoreType = "48 83 EC 28 E8 ? ? ? ? 48 8B 15 ? ? ? ? 48 8B 48 08";
        public const string update_global_vars = "48 8B 0D ? ? ? ? 4C 8D 05 ? ? ? ? 48 85 D2 48 8D 05";
        public const string update_post_processing_v2 = "48 89 AC 24 B8 00 00 00 45 33 ED 0F 29 74 24 70";
        public const string view_matrix_ptr = "48 8D 0D ? ? ? ? 48 89 44 24 ? 48 89 4C 24 ? 4C 8D 0D";
    }
    public static class engine2
    {
        public const string BuildNumber_addr = "89 05 ? ? ? ? 48 8D 0D ? ? ? ? FF 15 ? ? ? ? 48 8B 0D";
        public const string CCommand_Tokenize = "48 89 6C 24 20 4C 89 44 24 18 56 57 41 54 41 56";
        public const string CGameClient_ClientCommand = "48 8B C4 4C 89 40 18 4C 89 48 20 55 53 57 48 8D";
        public const string CHLTVClient_ExecuteStringCommand = "40 53 56 48 81 EC 48 07 00 00 48 8B F1 48 8B DA";
        public const string CSplitScreenSlot = "48 83 EC 58 4C 8B D2 45 85 C0 0F 85 ? ? ? ?";
        public const string Cvar_RegisterConCommand = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 60 44 8B 15 89";
        public const string Cvar_RegisterConVar = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 54 41 56 41 57 48 81 EC D0 00 00";
        public const string DisablePvsAccessor = "48 8D 0D ? ? ? ? 33 D2 FF 50 30 48 8B CF C7";
        public const string Engine__GetScreenAspectRatio = "48 89 5C 24 08 57 48 83 EC 20 8B FA 48 8D 0D 0D";
        public const string Engine__PVSManager_ptr = "48 8D 0D ? ? ? ? 33 D2 FF 50";
        public const string Engine__RunPrediction = "40 55 41 56 48 83 EC 68 80 B9 00 01 00 00 00 8B";
        public const string Engine_Disconnect_main = "48 89 5C 24 20 55 57 41 54 48 8B EC 48 83 EC 70";
        public const string Engine_HLTVClient_ExecuteStringCommand = "40 53 56 48 81 EC 48 07 00 00 48 8B F1 48 8B DA";
        public const string Engine_HostStateMgr_QueueNewRequest = "48 89 6C 24 18 48 89 7C 24 20 41 56 48 83 EC 30 48 8B EA 48";
        public const string Engine_HostStateMgr_QueueNewRequest = "48 89 6C 24 18 48 89 7C 24 20 41 56 48 83 EC 30 48 8B EA 48";
        public const string Engine_LoadGameInfo = "40 55 56 41 56 48 8D 6C 24 F0 48 81 EC 10 01 00";
        public const string Engine_MountAddon = "48 85 D2 0F 84 ? ? ? ? 48 8B C4 44 88 40 18";
        public const string Engine_NetTimeoutDisconnect = "40 53 55 56 57 41 56 48 81 EC 80 00 00 00 0F 29";
        public const string Engine_NetworkGameClient_Connect = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 40 44 89 81 3C";
        public const string Engine_NetworkGameClient_SetSignonState = "44 89 44 24 18 89 54 24 10 55 53 56 57 41 55 41";
        public const string Engine_RegisterConCommand = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 60 44 8B 15 89";
        public const string Engine_RegisterConVar = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 54 41 56 41 57 48 81 EC D0 00 00";
        public const string IsInGame = "48 8B 05 ? ? ? ? 48 85 C0 74 15 80 B8 1F 14";
        public const string NetworkGameClient_ptr = "48 89 3D ? ? ? ? FF 87";
        public const string WindowHeight_addr = "8B 05 ? ? ? ? 89 03";
        public const string WindowWidth_addr = "8B 05 ? ? ? ? 89 07";
    }
    public static class filesystem_stdio
    {
        public const string FullFileSystem_ptr = "8B 41 28 C3 CC CC CC CC CC CC CC CC CC CC CC CC 48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 8D 05 ? ? ? ? C3";
    }
    public static class inputsystem
    {
        public const string InputSystemSvc_ptr = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 40 53 48 83 EC 20 33 DB";
        public const string InputSystem_ptr = "48 89 05 ? ? ? ? 33 C0";
    }
    public static class matchmaking
    {
        public const string GameTypes_ptr = "48 8D 0D ? ? ? ? FF 90";
    }
    public static class materialsystem2
    {
        public const string CMaterial2_CompileComboAndGetVariables_DynamicShaderCompile = "48 89 54 24 10 55 41 55 48 8D 6C 24 F8 48 81 EC";
        public const string CMaterial2_GetMode = "48 89 5C 24 18 57 48 83 EC 30 8B 02 48 8B D9 39";
        public const string CMaterial2_GetVertexShaderInputSignature = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 30 F6 41";
        public const string CMaterial2_GetVertexShaderInputSignature = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 30 F6 41";
        public const string CMaterial2_LoadShadersAndSetupModes = "44 89 44 24 18 48 89 54 24 10 53 56 41 54 41 55";
        public const string CMaterialLayer_ApplyMaterialVarsForBatch = "4C 89 4C 24 20 4C 89 44 24 18 48 89 54 24 10 53";
        public const string CMaterialLayer_BuildPassCommandData = "89 54 24 10 55 53 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 58 FE FF FF";
        public const string CMaterialLayer_ComputeWorkItemsToSetupStaticCombosForMode = "48 8B CF 88 44 24 20 49 8B D2 E8 ? ? ? ? 84";
        public const string CMaterialLayer_CreateCommandBuffer = "4C 8B DC 45 89 4B 20 45 89 43 18 49 89 53 10 49";
        public const string CMaterialSystem2_BindIdentityInstanceIDBufferAndSetRenderState = "40 55 41 54 41 55 41 57 48 8D AC 24 98 FD FF FF";
        public const string CMaterialSystem2_DynamicShaderCompile_ProcessQueue = "48 83 39 00 74 06 FF 15 E4 53 0B 00 44 8B C7 45";
        public const string CMaterialSystem2_DynamicShaderCompile_ReloadAndSync = "48 83 EC 20 48 8B 35 ? ? ? ? 48 8B CE E8 CB";
        public const string CMaterialSystem2_DynamicShaderCompile_UnloadAllMaterials = "48 8B C4 41 57 48 81 EC B0 00 00 00 F6 81 80 05";
        public const string CMaterialSystem2_FrameUpdate = "48 89 4C 24 08 55 53 56 57 41 54 41 56 48 8B EC";
        public const string CMaterialSystem2_GetErrorMaterial = "48 8B 05 ? ? ? ? 48 8B 48 30 48 85 C9 75 31";
        public const string CMaterialSystem2_Init = "40 55 53 41 55 41 56 41 57 48 8D AC 24 20 FF FF";
        public const string CMaterial_SetVariableAndRenderState = "48 89 5C 24 08 4C 89 44 24 18 48 89 54 24 10 55 56 57 41 54 41 55 41 56 41 57 48 8B EC 48 83 EC 70 4C 8B BD 90 00 00 00";
        public const string CVfxProgramData_FindOrCreateStaticComboDataInCache = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 54 41 55 41 56 41 57 48 83 EC 20 33 ED 4C 8B";
        public const string CVfxProgramData_FindOrCreateStaticComboData_CacheGate = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 57 48 83";
        public const string CVfxProgramData_FindOrLoadStaticComboData = "4C 89 4C 24 20 48 89 54 24 10 48 89 4C 24 08 55";
        public const string FindParameter = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8B 59 20 48";
        public const string MatSys__PrepareSceneMaterial = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 30 48 8B 59 20 48";
        public const string UpdateParameter = "48 89 7C 24 20 41 56 48 83 EC 20 8B 81 14 04 00";
    }
    public static class networksystem
    {
        public const string CNetChan_ProcessMessages = "48 8B C4 53 57 41 54 41 56 48 81 EC A8 00 00 00";
        public const string CNetworkSystem_Init = "40 55 53 57 41 54 41 55 41 57 48 8D AC 24 98 FC";
        public const string CNetworkSystem_RegisterNetMessageHandlerAbstract = "48 89 5C 24 10 48 89 6C 24 18 57 41 56 41 57 48 83 EC 50 4C";
        public const string NetSystem_CNetChan_ProcessMessages = "48 8B C4 53 57 41 54 41 56 48 81 EC A8 00 00 00";
        public const string NetworkSystem_ptr = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 83 EC 28 BA FF FF FF";
    }
    public static class particles
    {
        public const string GetParticleManager = "48 8B 05 ? ? ? ? C3 ? ? ? ? ? ? ? ? 48 83 EC 28 8B 0D";
        public const string Particles__CParticleSystemMgr_CreateParticleCollection = "4C 8B DC 49 89 5B 10 49 89 6B 18 49 89 73 20 57 41 56 41 57";
        public const string Particles__CParticleSystemMgr_FindParticleSystem = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 41 56 41 57 48 81 EC 40";
        public const string Particles__DrawArray = "40 55 53 56 57 48 8D 6C 24 F8 48 81 EC 08 01 00";
        public const string Particles__FindKeyVar = "48 89 5C 24 08 57 48 81 EC C0 00 00 00 33 C0 8B";
        public const string Particles__SetMaterialShaderType = "48 89 5C 24 10 48 89 6C 24 18 56 57 41 54 41 56 41 57 48 81";
    }
    public static class rendersystemdx11
    {
        public const string CRenderDeviceBase_CreateConstantBuffer = "48 89 5C 24 08 48 89 74 24 10 48 89 7C 24 18 55 41 56 41 57 48 8D 6C 24";
        public const string CRenderDeviceDx11_BeginSubmittingDisplayLists = "48 89 5C 24 08 57 48 83 EC 50 48 8B F9 48 8B DA";
        public const string CRenderDeviceDx11_CompileShaderSourceMain = "4C 8B DC 49 89 5B 08 57 48 83 EC 70 4D 8B D0 48";
        public const string RenderDeviceMgr_ptr = "8B 5C 24 38 48 83 C4 20 5E C3 CC CC CC CC CC CC 48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 8D 05 ? ? ? ? C3";
        public const string RenderSystemDx11_SetHardwareGammaRamp = "48 89 5C 24 18 57 B8 B0 40 00 00 E8 ? ? ? ?";
        public const string RenderSystemDx11_SetMode = "44 89 4C 24 20 44 89 44 24 18 89 54 24 10 55 53";
    }
    public static class resourcesystem
    {
        public const string ResourceSystem_BlockingLoadResourceByName = "40 53 55 57 48 81 EC 80 00 00 00 48 8B 01 49 8B";
        public const string ResourceSystem_FindOrRegisterResourceByName = "48 89 5C 24 18 48 89 74 24 20 57 48 81 EC A0 00";
        public const string ResourceSystem_FrameUpdate = "44 88 4C 24 20 44 89 44 24 18 89 54 24 10 55 56";
    }
    public static class scenesystem
    {
        public const string BuildSceneInfoGpu = "4C 89 4C 24 20 4C 89 44 24 18 48 89 4C 24 08 55 48 8D AC 24 00 E3 FF FF";
        public const string CSceneAnimatableObject__GeneratePrimitives = "48 8B C4 48 89 58 08 48 89 50 10 55 56 57 41 54 41 55 41 56 41 57 48 81";
        public const string CSceneAnimatableObject_GeneratePrimitives = "48 8B C4 48 89 58 08 48 89 50 10 55 56 57 41 54 41 55 41 56 41 57 48 81";
        public const string CSceneSkyBoxObject_DrawSkyboxArray = "45 85 C9 0F 8E ? ? ? ? 4C 8B DC 55 41 56 49";
        public const string CSceneSystem_CreateStaticShape = "48 8B C4 48 89 48 08 55 41 54 41 56 48 8D 68 D8";
        public const string CSceneSystem_InitGfxObjects = "40 55 53 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 08 FE FF";
        public const string CSceneSystem_RenderViewLayer_Dispatch = "48 8B C4 48 89 48 08 55 53 56 57 41 54 41 55 41 56 41 57 48 8D A8 B8 FE";
        public const string CSceneSystem_Thread_CullView = "4C 89 44 24 18 48 89 54 24 10 48 89 4C 24 08 55 53 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 E1";
        public const string DrawAggregateSceneObjectArray = "48 8B C4 48 89 50 10 48 89 48 08 55 53 56 57 41 54 41 55 41 56 41 57 48 8D A8 38 F9";
        public const string DrawObject_legacy = "48 8B C4 53 57 41 54 48 81 EC D0 00 00 00 49 63";
        public const string DrawSkyboxArray = "45 85 C9 0F 8E ? ? ? ? 4C 8B DC 55 41 56 49";
        public const string SceneSystem__DrawAggeregateObject = "48 8B C4 4C 89 48 20 4C 89 40 18 48 89 50 10 55 53 41 57 48";
        public const string SceneSystem__DrawArrayLight = "48 89 5C 24 08 48 89 6C 24 18 48 89 54 24 10 56 57 41 56 48";
        public const string SceneSystem_Thread_RenderSceneDrawList = "40 55 53 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 E1 48 81 EC D8 00 00";
        public const string SceneSystem_ptr = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 8D 0D ? ? ? ? E9";
    }
    public static class schemasystem
    {
        public const string CSchemaSystem_InstallSchemaBindings = "40 53 48 83 EC 20 48 8B DA 48 8B D1 48 8D 0D 8D";
        public const string CSchemaSystem_RegisterModuleAndBuiltins = "48 89 54 24 10 53 56 57 41 55 41 56 41 57 48 83";
        public const string CSchemaSystem_VerifySchemaBindingConsistency = "88 54 24 10 55 53 57 41 54 41 55 48 8B EC 48 81";
        public const string SchemaSystem_ptr = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 89 5C 24 08 48 89 74";
    }
    public static class soundsystem
    {
        public const string CSosOperatorSystem_StartSoundEvent = "40 53 55 56 48 83 EC 20 83 B9 EC 24 00 00 00 49";
        public const string SoundSystem__PlayVSound = "48 8B C4 48 89 58 08 57 48 81 EC A0 00 00 00 33";
        public const string SoundSystem__SomeUtlSymbolFunc = "48 89 74 24 18 57 48 83 EC 20 48 63 F2 48 8B F9";
        public const string SoundSystem_ptr = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 89 15";
    }
    public static class tier0
    {
        public const string CVar_ptr = "48 8D 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC E9";
        public const string Tier0__LoadKeyValues = "48 89 5C 24 10 48 89 6C 24 18 48 89 7C 24 20 41 54 41 56 41 57 48 83 EC 40 45 33 E4";
        public const string Tier0__UtlBuffer = "48 89 5C 24 08 57 48 83 EC 20 8B 41 04 8D 7A 08";
    }
    public static class vphysics2
    {
        public const string VPhysics2_Startup = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 54 41 56 41 57 48 83 EC 70 48 83";
    }
}
