// Generated by cs2-sdk - https://cs2-sdk.com
#pragma once

#include <cstdint>

namespace cs2::ifaces { inline constexpr std::uint32_t CS2_BUILD = 14161; }

namespace cs2::ifaces {

    namespace animationsystem_dll {
        inline void* AnimationSystemUtils_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x812190); }
        inline void* AnimationSystem_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x80A0B0); }
    } // namespace animationsystem_dll

    namespace client_dll {
        inline void* ClientToolsInfo_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x20531C0); }
        inline void* EmptyWorldService001_Client(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x2016AF0); }
        inline void* GameClientExports001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x204FE60); }
        inline void* LegacyGameUI001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x206B5D0); }
        inline void* Source2Client002(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x2329F90); }
        inline void* Source2ClientConfig001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x229BE20); }
        inline void* Source2ClientPrediction001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x205A610); }
        inline void* Source2ClientUI001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x2069B30); }
    } // namespace client_dll

    namespace engine2_dll {
        inline void* BenchmarkService001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x6129A0); }
        inline void* BugService001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x8CA9E0); }
        inline void* ClientServerEngineLoopService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x90C0E0); }
        inline void* ClientServerSharedHandleSystem001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x90B690); }
        inline void* EngineGameUI001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x6102A0); }
        inline void* EngineServiceMgr001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x90B9C0); }
        inline void* GameEventSystemClientV001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x90BCA0); }
        inline void* GameEventSystemServerV001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x90BDD0); }
        inline void* GameResourceServiceClientV001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x612AA0); }
        inline void* GameResourceServiceServerV001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x612B00); }
        inline void* GameUIService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x8CAE10); }
        inline void* HostStateMgr001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x6132E0); }
        inline void* INETSUPPORT_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x60C040); }
        inline void* InputService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x8CB100); }
        inline void* KeyValueCache001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x613390); }
        inline void* MapListService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x909F70); }
        inline void* NetworkClientService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x90A100); }
        inline void* NetworkP2PService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x90A440); }
        inline void* NetworkServerService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x90A5F0); }
        inline void* NetworkService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x612C70); }
        inline void* RenderService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x90A860); }
        inline void* ScreenshotService001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x90AB20); }
        inline void* SimpleEngineLoopService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x6133F0); }
        inline void* SoundService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x612CB0); }
        inline void* Source2EngineToClient001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x60FBA0); }
        inline void* Source2EngineToClientStringTable001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x60FC00); }
        inline void* Source2EngineToServer001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x60FC78); }
        inline void* Source2EngineToServerStringTable001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x60FCA0); }
        inline void* SplitScreenService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x612F90); }
        inline void* StatsService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x90AEE0); }
        inline void* ToolService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x613150); }
        inline void* VENGINE_GAMEUIFUNCS_VERSION005(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x610330); }
        inline void* VProfService_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x613190); }
    } // namespace engine2_dll

    namespace filesystem_stdio_dll {
        inline void* VAsyncFileSystem2_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x2159E0); }
        inline void* VFileSystem017(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x2157A0); }
    } // namespace filesystem_stdio_dll

    namespace host_dll {
        inline void* DebugDrawQueueManager001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x139060); }
        inline void* GameModelInfo001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1390A0); }
        inline void* GameSystem2HostHook(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1390E0); }
        inline void* HostUtils001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x148AB0); }
        inline void* PredictionDiffManager001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1391F0); }
        inline void* SaveRestoreDataVersion001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x139320); }
        inline void* SinglePlayerSharedMemory001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x139350); }
        inline void* Source2Host001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1393C0); }
    } // namespace host_dll

    namespace imemanager_dll {
        inline void* IMEManager001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x36B20); }
    } // namespace imemanager_dll

    namespace inputsystem_dll {
        inline void* InputStackSystemVersion001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x40E30); }
        inline void* InputSystemVersion001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x42B50); }
    } // namespace inputsystem_dll

    namespace localize_dll {
        inline void* Localize_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x62180); }
    } // namespace localize_dll

    namespace matchmaking_dll {
        inline void* GameTypes001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1B0F80); }
        inline void* MATCHFRAMEWORK_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1B9060); }
    } // namespace matchmaking_dll

    namespace materialsystem2_dll {
        inline void* FontManager_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x15DE60); }
        inline void* MaterialUtils_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x145D40); }
        inline void* PostProcessingSystem_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x145C50); }
        inline void* TextLayout_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x145CD0); }
        inline void* VMaterialSystem2_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x15D750); }
    } // namespace materialsystem2_dll

    namespace meshsystem_dll {
        inline void* MeshSystem001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x150C20); }
    } // namespace meshsystem_dll

    namespace navsystem_dll {
        inline void* NavSystem001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x122930); }
    } // namespace navsystem_dll

    namespace networksystem_dll {
        inline void* FlattenedSerializersVersion001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x26E750); }
        inline void* NetworkMessagesVersion001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x296A60); }
        inline void* NetworkSystemVersion001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x287EA0); }
        inline void* SerializedEntitiesVersion001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x287F90); }
    } // namespace networksystem_dll

    namespace panorama_dll {
        inline void* PanoramaUIEngine001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x505D20); }
    } // namespace panorama_dll

    namespace panorama_text_pango_dll {
        inline void* PanoramaTextServices001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x2B8A40); }
    } // namespace panorama_text_pango_dll

    namespace panoramauiclient_dll {
        inline void* PanoramaUIClient001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x296420); }
    } // namespace panoramauiclient_dll

    namespace particles_dll {
        inline void* ParticleSystemMgr003(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x54A370); }
    } // namespace particles_dll

    namespace pulse_system_dll {
        inline void* IPulseSystem_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1F36A0); }
    } // namespace pulse_system_dll

    namespace rendersystemdx11_dll {
        inline void* RenderDeviceMgr001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x42B530); }
        inline void* RenderUtils_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x42BE28); }
        inline void* VRenderDeviceMgrBackdoor001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x42B5D0); }
    } // namespace rendersystemdx11_dll

    namespace resourcesystem_dll {
        inline void* ResourceSystem013(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x831E0); }
    } // namespace resourcesystem_dll

    namespace scenefilecache_dll {
        inline void* ResponseRulesCache001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0xF58F0); }
        inline void* SceneFileCache002(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0xF5A78); }
    } // namespace scenefilecache_dll

    namespace scenesystem_dll {
        inline void* RenderingPipelines_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x663BA0); }
        inline void* SceneSystem_002(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x8DB490); }
        inline void* SceneUtils_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x664AB0); }
    } // namespace scenesystem_dll

    namespace schemasystem_dll {
        inline void* SchemaSystem_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x76800); }
    } // namespace schemasystem_dll

    namespace server_dll {
        inline void* EmptyWorldService001_Server(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1BF1D60); }
        inline void* EntitySubclassUtilsV001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1B9D3A0); }
        inline void* NavGameTest001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1C9E2E0); }
        inline void* ServerToolsInfo_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1C4B2C8); }
        inline void* Source2GameClients001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1C49D20); }
        inline void* Source2GameDirector001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1DE38F0); }
        inline void* Source2GameEntities001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1C4A9D0); }
        inline void* Source2Server001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1C4A820); }
        inline void* Source2ServerConfig001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1F00BA8); }
        inline void* customnavsystem001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x1B7E698); }
    } // namespace server_dll

    namespace soundsystem_dll {
        inline void* SoundOpSystem001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x5129B0); }
        inline void* SoundOpSystemEdit001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x512870); }
        inline void* SoundSystem001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x512360); }
        inline void* VMixEditTool001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x594879F); }
    } // namespace soundsystem_dll

    namespace steamaudio_dll {
        inline void* SteamAudio001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x25E620); }
    } // namespace steamaudio_dll

    namespace steamclient64_dll {
        inline void* IVALIDATE001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BE0B8); }
        inline void* SteamClient006(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB520); }
        inline void* SteamClient007(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB528); }
        inline void* SteamClient008(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB530); }
        inline void* SteamClient009(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB538); }
        inline void* SteamClient010(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB540); }
        inline void* SteamClient011(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB548); }
        inline void* SteamClient012(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB550); }
        inline void* SteamClient013(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB558); }
        inline void* SteamClient014(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB560); }
        inline void* SteamClient015(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB568); }
        inline void* SteamClient016(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB570); }
        inline void* SteamClient017(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB578); }
        inline void* SteamClient018(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB580); }
        inline void* SteamClient019(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB588); }
        inline void* SteamClient020(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB590); }
        inline void* SteamClient021(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB598); }
        inline void* SteamClient022(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB5A0); }
        inline void* SteamClient023(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16BB5A8); }
        inline void* p2pvoice002(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x14E627F); }
        inline void* p2pvoicesingleton002(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x16960F0); }
    } // namespace steamclient64_dll

    namespace tier0_dll {
        inline void* TestScriptMgr001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x39E6F0); }
        inline void* VEngineCvar007(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x3A93B0); }
        inline void* VProcessUtils002(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x39E690); }
        inline void* VStringTokenSystem001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x3D00B0); }
    } // namespace tier0_dll

    namespace v8system_dll {
        inline void* Source2V8System001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x31730); }
    } // namespace v8system_dll

    namespace vconcomm_dll {
        inline void* VConComm001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x395C0); }
    } // namespace vconcomm_dll

    namespace vphysics2_dll {
        inline void* VPhysics2_Interface_001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x40DDA0); }
    } // namespace vphysics2_dll

    namespace vscript_dll {
        inline void* VScriptManager010(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x13B410); }
    } // namespace vscript_dll

    namespace vstdlib_s64_dll {
        inline void* IVALIDATE001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x6F990); }
        inline void* VEngineCvar002(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x6E070); }
    } // namespace vstdlib_s64_dll

    namespace worldrenderer_dll {
        inline void* WorldRendererMgr001(std::uintptr_t module_base) noexcept { return reinterpret_cast<void*>(module_base + 0x225C60); }
    } // namespace worldrenderer_dll

} // namespace sdk::ifaces
